import type { CuratedTemplate } from "@/lib/volleyball";

export const LIBRARY_TEMPLATES: CuratedTemplate[] = [
  {
    slug: "toque-sem-medo",
    category: "Sub-11",
    hook: "Seus atletas têm medo da bola?",
    title: "Toque Sem Medo",
    subtitle: "Fundamentos de passe e recepção",
    objective: "Perder o medo do contato com a bola e consolidar a postura de passe e manchete.",
    courtSetup: "Quadra reduzida",
    totalDurationMin: 50,
    playersCount: 10,
    intensity: 1,
    materials: ["1 bola por dupla", "8 cones"],
    coverFrom: "#3B82F6",
    coverTo: "#1D4ED8",
    blocks: [
      {
        order: 1,
        title: "Aquecimento — bola ao alto em dupla",
        durationMin: 15,
        description: "Em duplas, os atletas jogam a bola ao alto para si mesmos e depois passam para o parceiro, mantendo a bola sempre no ar.",
        coachingPoints: ["Mãos em forma de diamante acima da testa", "Joelhos sempre flexionados", "Olhar a bola até o contato"],
        technicalActions: { offensive: ["Toque de dedos"], defensive: [] },
        tacticalPrinciple: "Familiarização com o contato da bola",
        variants: { harder: "Aumentar a distância entre a dupla", easier: "Permitir a bola quicar uma vez antes do toque" },
        diagram: {
          players: [
            { x: 30, y: 70, team: "A", number: 1 },
            { x: 70, y: 70, team: "A", number: 2 },
          ],
          arrows: [{ from: { x: 30, y: 70 }, to: { x: 70, y: 70 }, type: "set", order: 1 }],
          cones: [],
          balls: [{ x: 50, y: 55 }],
        },
      },
      {
        order: 2,
        title: "Circuito de manchete nos cones",
        durationMin: 20,
        description: "Cones espalhados pela quadra; o treinador lança a bola e o atleta se desloca até o cone mais próximo para executar a manchete de volta ao treinador.",
        coachingPoints: ["Base alargada e estável", "Braços firmes e estendidos", "Contato no antebraço, não nas mãos"],
        technicalActions: { offensive: [], defensive: ["Manchete de recepção"] },
        tacticalPrinciple: "Deslocamento até a bola antes do contato",
        variants: { harder: "Lançar a bola com mais velocidade e variação de ângulo", easier: "Reduzir a distância dos cones ao treinador" },
        diagram: {
          players: [{ x: 50, y: 75, team: "A", number: 3 }],
          arrows: [{ from: { x: 50, y: 20 }, to: { x: 50, y: 75 }, type: "serve", order: 1 }],
          cones: [{ x: 30, y: 75 }, { x: 70, y: 75 }, { x: 50, y: 85 }],
          balls: [{ x: 50, y: 20 }],
        },
      },
      {
        order: 3,
        title: "Jogo 3x3 só de toque e manchete",
        durationMin: 15,
        description: "Jogo reduzido em que só é permitido jogar a bola com toque de dedos ou manchete, sem ataque, pontuando a cada 3 toques completos do time.",
        coachingPoints: ["Comunicação para não deixar a bola cair", "Reposicionar após cada contato"],
        technicalActions: { offensive: ["Construção de jogada simples"], defensive: ["Cobertura de quadra"] },
        tacticalPrinciple: "Aplicação dos fundamentos em contexto de jogo",
        variants: { harder: "Exigir 3 toques obrigatórios antes de passar a bola", easier: "Permitir qualquer número de toques" },
        diagram: {
          players: [
            { x: 25, y: 80, team: "A", number: 1 },
            { x: 50, y: 85, team: "A", number: 2 },
            { x: 75, y: 80, team: "A", number: 3 },
            { x: 25, y: 20, team: "B", number: 4 },
            { x: 50, y: 15, team: "B", number: 5 },
            { x: 75, y: 20, team: "B", number: 6 },
          ],
          arrows: [],
          cones: [],
          balls: [{ x: 50, y: 50 }],
        },
      },
    ],
  },
  {
    slug: "saque-certeiro",
    category: "Sub-13",
    hook: "Os saques sempre caem na rede?",
    title: "Saque Certeiro",
    subtitle: "Técnica e consistência de saque",
    objective: "Melhorar a técnica do saque por baixo e por cima, priorizando consistência sobre potência.",
    courtSetup: "Quadra completa",
    totalDurationMin: 55,
    playersCount: 12,
    intensity: 2,
    materials: ["1 bola por atleta", "4 cones", "fita para marcar zonas"],
    coverFrom: "#22C55E",
    coverTo: "#15803D",
    blocks: [
      {
        order: 1,
        title: "Aquecimento — arremesso e ritmo de braço",
        durationMin: 10,
        description: "Arremesso de bola por cima da cabeça simulando o movimento do saque, sem quadra, apenas para ganhar ritmo de braço.",
        coachingPoints: ["Armar o braço atrás do ombro", "Passo com o pé oposto ao braço de ataque"],
        technicalActions: { offensive: ["Preparação de saque"], defensive: [] },
        tacticalPrinciple: "Memorização do gesto técnico",
        variants: { harder: "Aumentar a distância do arremesso", easier: "Reduzir a amplitude do movimento" },
        diagram: {
          players: [{ x: 50, y: 90, team: "A", number: 7 }],
          arrows: [{ from: { x: 50, y: 90 }, to: { x: 50, y: 40 }, type: "serve", order: 1 }],
          cones: [],
          balls: [{ x: 50, y: 90 }],
        },
      },
      {
        order: 2,
        title: "Saque por zonas",
        durationMin: 25,
        description: "Quadra dividida em 4 zonas marcadas com cones; cada atleta saca tentando acertar a zona indicada pelo treinador, acumulando pontos por acerto.",
        coachingPoints: ["Consistência antes de potência", "Repetir a mesma rotina antes de cada saque"],
        technicalActions: { offensive: ["Saque direcionado"], defensive: [] },
        tacticalPrinciple: "Saque como arma tática, não só início de jogada",
        variants: { harder: "Reduzir o tamanho das zonas-alvo", easier: "Aumentar o tamanho das zonas e permitir saque por baixo" },
        diagram: {
          players: [{ x: 50, y: 92, team: "A", number: 7 }],
          arrows: [{ from: { x: 50, y: 92 }, to: { x: 25, y: 15 }, type: "serve", order: 1 }],
          cones: [{ x: 10, y: 10 }, { x: 45, y: 10 }, { x: 55, y: 10 }, { x: 90, y: 10 }],
          balls: [{ x: 50, y: 92 }],
        },
      },
      {
        order: 3,
        title: "Disputa de saques em duplas",
        durationMin: 20,
        description: "Duplas competem entre si: quem errar mais saques em uma série de 5 faz uma tarefa física leve, incentivando foco sob leve pressão.",
        coachingPoints: ["Manter a rotina mesmo sob pressão", "Respiração antes do saque"],
        technicalActions: { offensive: ["Saque sob pressão"], defensive: [] },
        tacticalPrinciple: "Transferência da técnica para situação de pressão",
        variants: { harder: "Reduzir para 3 tentativas", easier: "Aumentar para 8 tentativas" },
        diagram: {
          players: [
            { x: 35, y: 92, team: "A", number: 1 },
            { x: 65, y: 92, team: "B", number: 2 },
          ],
          arrows: [
            { from: { x: 35, y: 92 }, to: { x: 35, y: 20 }, type: "serve", order: 1 },
            { from: { x: 65, y: 92 }, to: { x: 65, y: 20 }, type: "serve", order: 2 },
          ],
          cones: [],
          balls: [{ x: 35, y: 92 }, { x: 65, y: 92 }],
        },
      },
    ],
  },
  {
    slug: "ataque-matador",
    category: "Sub-13",
    hook: "Seus atacantes erram o ataque na rede ou pra fora?",
    title: "Ataque Matador",
    subtitle: "Aproximação e finalização de ataque",
    objective: "Corrigir o tempo de aproximação e o contato na bola para finalizações mais eficientes.",
    courtSetup: "Zona de ataque",
    totalDurationMin: 60,
    playersCount: 10,
    intensity: 2,
    materials: ["6 bolas", "4 cones", "1 rede"],
    coverFrom: "#F97316",
    coverTo: "#C2410C",
    blocks: [
      {
        order: 1,
        title: "Aproximação sem bola",
        durationMin: 10,
        description: "Repetição da aproximação de 3 passos e do salto sem bola, com o treinador corrigindo o tempo de cada passo.",
        coachingPoints: ["Último passo mais longo e explosivo", "Braços para trás na preparação do salto"],
        technicalActions: { offensive: ["Aproximação de ataque"], defensive: [] },
        tacticalPrinciple: "Base biomecânica do ataque",
        variants: { harder: "Adicionar troca de ritmo antes da aproximação", easier: "Reduzir para 2 passos" },
        diagram: {
          players: [{ x: 30, y: 70, team: "A", number: 9 }],
          arrows: [{ from: { x: 30, y: 70 }, to: { x: 30, y: 45 }, type: "move", order: 1 }],
          cones: [{ x: 30, y: 55 }],
          balls: [],
        },
      },
      {
        order: 2,
        title: "Ataque com bola lançada à mão",
        durationMin: 25,
        description: "Treinador lança a bola perto da rede para o atacante executar aproximação, salto e finalização cruzada ou de linha.",
        coachingPoints: ["Contato com a mão espalmada e braço estendido", "Olhar o bloqueio antes de decidir o ângulo"],
        technicalActions: { offensive: ["Ataque cruzado", "Ataque de linha"], defensive: [] },
        tacticalPrinciple: "Leitura do bloqueio para escolha de ângulo",
        variants: { harder: "Adicionar um bloqueador passivo", easier: "Lançar a bola sempre no mesmo ponto" },
        diagram: {
          players: [
            { x: 25, y: 70, team: "A", number: 9 },
            { x: 60, y: 40, team: "N", number: 0 },
          ],
          arrows: [
            { from: { x: 60, y: 40 }, to: { x: 25, y: 55 }, type: "set", order: 1 },
            { from: { x: 25, y: 55 }, to: { x: 15, y: 15 }, type: "spike", order: 2 },
          ],
          cones: [],
          balls: [{ x: 60, y: 40 }],
        },
      },
      {
        order: 3,
        title: "Finalização contra bloqueio simples",
        durationMin: 25,
        description: "Sequência completa de levantamento e ataque contra um bloqueador, obrigando o atacante a decidir entre cruzada, linha ou largada.",
        coachingPoints: ["Variar as finalizações", "Comunicação com o levantador"],
        technicalActions: { offensive: ["Ataque com decisão"], defensive: ["Bloqueio simples"] },
        tacticalPrinciple: "Tomada de decisão sob oposição",
        variants: { harder: "Adicionar um segundo bloqueador", easier: "Remover o bloqueio e focar só na finalização" },
        diagram: {
          players: [
            { x: 20, y: 75, team: "A", number: 9 },
            { x: 50, y: 65, team: "A", number: 5 },
            { x: 20, y: 30, team: "B", number: 2 },
          ],
          arrows: [
            { from: { x: 50, y: 65 }, to: { x: 20, y: 55 }, type: "set", order: 1 },
            { from: { x: 20, y: 55 }, to: { x: 25, y: 15 }, type: "spike", order: 2 },
            { from: { x: 20, y: 30 }, to: { x: 22, y: 25 }, type: "block", order: 3 },
          ],
          cones: [],
          balls: [{ x: 50, y: 65 }],
        },
      },
    ],
  },
  {
    slug: "a-muralha",
    category: "Sub-15",
    hook: "Seu bloqueio salta cedo demais e cai na rede?",
    title: "A Muralha",
    subtitle: "Tempo e posicionamento de bloqueio",
    objective: "Ajustar o tempo de salto do bloqueio em relação ao levantamento adversário.",
    courtSetup: "Meia quadra",
    totalDurationMin: 55,
    playersCount: 10,
    intensity: 2,
    materials: ["6 bolas", "1 rede"],
    coverFrom: "#A855F7",
    coverTo: "#6D28D9",
    blocks: [
      {
        order: 1,
        title: "Deslocamento lateral + salto",
        durationMin: 15,
        description: "Deslocamento lateral em passadas curtas ao longo da rede seguido de salto vertical sem contato, focando em não invadir o espaço do adversário.",
        coachingPoints: ["Mãos próximas ao rosto na preparação", "Salto vertical, sem se jogar para frente"],
        technicalActions: { offensive: [], defensive: ["Deslocamento de bloqueio"] },
        tacticalPrinciple: "Base do deslocamento lateral",
        variants: { harder: "Aumentar a distância do deslocamento", easier: "Reduzir para deslocamento de um passo" },
        diagram: {
          players: [{ x: 30, y: 45, team: "B", number: 2 }],
          arrows: [{ from: { x: 30, y: 45 }, to: { x: 60, y: 45 }, type: "move", order: 1 }],
          cones: [],
          balls: [],
        },
      },
      {
        order: 2,
        title: "Leitura do levantador",
        durationMin: 20,
        description: "Um levantador simula diferentes levantamentos (rápido, alto, aberto) e o bloqueador deve se deslocar e saltar no tempo certo para cada tipo.",
        coachingPoints: ["Observar os ombros do levantador", "Ajustar o tempo de salto conforme a altura do levantamento"],
        technicalActions: { offensive: [], defensive: ["Leitura de bloqueio"] },
        tacticalPrinciple: "Antecipação tática baseada em pistas visuais",
        variants: { harder: "Adicionar dois atacantes simultâneos como opção", easier: "Avisar verbalmente o tipo de levantamento antes" },
        diagram: {
          players: [
            { x: 50, y: 60, team: "B", number: 3 },
            { x: 30, y: 45, team: "B", number: 2 },
            { x: 30, y: 20, team: "A", number: 9 },
          ],
          arrows: [
            { from: { x: 50, y: 60 }, to: { x: 30, y: 35 }, type: "set", order: 1 },
            { from: { x: 30, y: 45 }, to: { x: 30, y: 38 }, type: "block", order: 2 },
          ],
          cones: [],
          balls: [{ x: 50, y: 60 }],
        },
      },
      {
        order: 3,
        title: "Bloqueio duplo contra ataque real",
        durationMin: 20,
        description: "Situação de jogo com levantamento, ataque e bloqueio duplo, fechando o ângulo de ataque e cobrindo o bloqueio com um defensor atrás.",
        coachingPoints: ["Fechar as mãos na diagonal do atacante", "Comunicação entre os dois bloqueadores"],
        technicalActions: { offensive: [], defensive: ["Bloqueio duplo", "Cobertura de bloqueio"] },
        tacticalPrinciple: "Fechamento coletivo do bloqueio",
        variants: { harder: "Adicionar bloqueio triplo em jogadas de meio", easier: "Reduzir para bloqueio individual" },
        diagram: {
          players: [
            { x: 30, y: 40, team: "B", number: 2 },
            { x: 45, y: 40, team: "B", number: 3 },
            { x: 40, y: 65, team: "B", number: 6 },
            { x: 30, y: 15, team: "A", number: 9 },
          ],
          arrows: [{ from: { x: 30, y: 15 }, to: { x: 35, y: 30 }, type: "spike", order: 1 }],
          cones: [],
          balls: [{ x: 30, y: 15 }],
        },
      },
    ],
  },
  {
    slug: "leia-o-jogo",
    category: "Sub-15",
    hook: "Seu time não consegue ler o levantador adversário?",
    title: "Leia o Jogo",
    subtitle: "Leitura defensiva e antecipação",
    objective: "Desenvolver a leitura de jogo para antecipar ataques e se posicionar melhor na defesa.",
    courtSetup: "Quadra completa",
    totalDurationMin: 60,
    playersCount: 12,
    intensity: 2,
    materials: ["6 bolas", "coletes de 2 cores"],
    coverFrom: "#14B8A6",
    coverTo: "#0F766E",
    blocks: [
      {
        order: 1,
        title: "Manchete reativa",
        durationMin: 15,
        description: "Em duplas, um jogador ataca bolas leves para pontos variados e o outro reage com manchete, sem saber a direção antecipadamente.",
        coachingPoints: ["Postura pronta antes de cada bola", "Passos curtos e rápidos para se ajustar"],
        technicalActions: { offensive: [], defensive: ["Manchete de defesa"] },
        tacticalPrinciple: "Velocidade de reação",
        variants: { harder: "Aumentar a velocidade dos ataques", easier: "Avisar a direção antes de cada bola" },
        diagram: {
          players: [
            { x: 30, y: 80, team: "A", number: 4 },
            { x: 60, y: 20, team: "B", number: 1 },
          ],
          arrows: [{ from: { x: 60, y: 20 }, to: { x: 30, y: 80 }, type: "spike", order: 1 }],
          cones: [],
          balls: [{ x: 60, y: 20 }],
        },
      },
      {
        order: 2,
        title: "Defesa por sistema com leitura do levantador",
        durationMin: 25,
        description: "O time defensivo se posiciona de acordo com o sistema definido, ajustando conforme lê para onde o levantador adversário vai distribuir a bola.",
        coachingPoints: ["Observar os ombros e mãos do levantador", "Ajustar o sistema de defesa em bloco"],
        technicalActions: { offensive: [], defensive: ["Sistema defensivo", "Leitura de jogo"] },
        tacticalPrinciple: "Organização coletiva da defesa",
        variants: { harder: "Alternar entre dois sistemas defensivos na mesma sessão", easier: "Fixar um único sistema simples" },
        diagram: {
          players: [
            { x: 20, y: 85, team: "A", number: 5 },
            { x: 50, y: 90, team: "A", number: 6 },
            { x: 80, y: 85, team: "A", number: 1 },
            { x: 50, y: 55, team: "B", number: 3 },
          ],
          arrows: [{ from: { x: 50, y: 55 }, to: { x: 80, y: 25 }, type: "set", order: 1 }],
          cones: [],
          balls: [{ x: 50, y: 55 }],
        },
      },
      {
        order: 3,
        title: "Jogo com pontuação bônus por defesa lida",
        durationMin: 20,
        description: "Jogo 6x6 em que toda defesa bem posicionada antecipadamente (antes do ataque) vale ponto bônus, incentivando a leitura constante.",
        coachingPoints: ["Comunicação verbal constante", "Nunca ficar estático esperando a bola"],
        technicalActions: { offensive: ["Sistema de ataque"], defensive: ["Leitura e antecipação"] },
        tacticalPrinciple: "Aplicação da leitura em contexto competitivo",
        variants: { harder: "Dobrar os pontos bônus para aumentar o incentivo", easier: "Remover a pontuação bônus e só observar" },
        diagram: {
          players: [
            { x: 20, y: 85, team: "A", number: 4 },
            { x: 50, y: 90, team: "A", number: 5 },
            { x: 80, y: 85, team: "A", number: 6 },
            { x: 20, y: 15, team: "B", number: 1 },
            { x: 50, y: 10, team: "B", number: 2 },
            { x: 80, y: 15, team: "B", number: 3 },
          ],
          arrows: [],
          cones: [],
          balls: [{ x: 50, y: 50 }],
        },
      },
    ],
  },
  {
    slug: "ritmo-de-rodizio",
    category: "Sub-17",
    hook: "O rodízio do seu time desanda no meio do set?",
    title: "Ritmo de Rodízio",
    subtitle: "Organização tática e rodízio",
    objective: "Consolidar as posições de rotação e as trocas pós-saque/pós-recepção sem confusão.",
    courtSetup: "Quadra completa",
    totalDurationMin: 65,
    playersCount: 12,
    intensity: 2,
    materials: ["6 bolas", "cartazes numerados de 1 a 6"],
    coverFrom: "#6366F1",
    coverTo: "#4338CA",
    blocks: [
      {
        order: 1,
        title: "Rodízio a seco",
        durationMin: 15,
        description: "Time se posiciona nas 6 posições de rotação e gira sem bola, o treinador apita e todos avançam uma posição, corrigindo erros de posicionamento.",
        coachingPoints: ["Memorizar a ordem de rotação", "Checar a posição do companheiro ao lado"],
        technicalActions: { offensive: [], defensive: [] },
        tacticalPrinciple: "Base do sistema de rotação",
        variants: { harder: "Fazer o rodízio de olhos fechados até a posição", easier: "Usar cartazes numerados no chão como referência" },
        diagram: {
          players: [
            { x: 20, y: 85, team: "A", number: 1 },
            { x: 50, y: 90, team: "A", number: 6 },
            { x: 80, y: 85, team: "A", number: 5 },
            { x: 20, y: 60, team: "A", number: 2 },
            { x: 50, y: 65, team: "A", number: 3 },
            { x: 80, y: 60, team: "A", number: 4 },
          ],
          arrows: [{ from: { x: 20, y: 85 }, to: { x: 20, y: 60 }, type: "move", order: 1 }],
          cones: [],
          balls: [],
        },
      },
      {
        order: 2,
        title: "Transição pós-saque para o sistema base",
        durationMin: 25,
        description: "Após o saque, o time se movimenta rapidamente para o sistema de recepção ou defesa combinado, treinando a velocidade de transição.",
        coachingPoints: ["Sair correndo assim que a bola sai da mão", "Manter as posições combinadas"],
        technicalActions: { offensive: [], defensive: ["Transição de sistema"] },
        tacticalPrinciple: "Velocidade de organização pós-saque",
        variants: { harder: "Cronometrar o tempo de organização", easier: "Fazer a transição em câmera lenta primeiro" },
        diagram: {
          players: [
            { x: 50, y: 92, team: "A", number: 1 },
            { x: 20, y: 80, team: "A", number: 5 },
            { x: 50, y: 85, team: "A", number: 6 },
            { x: 80, y: 80, team: "A", number: 4 },
          ],
          arrows: [{ from: { x: 50, y: 92 }, to: { x: 30, y: 30 }, type: "serve", order: 1 }],
          cones: [],
          balls: [{ x: 50, y: 92 }],
        },
      },
      {
        order: 3,
        title: "Set completo com rotação real",
        durationMin: 25,
        description: "Jogo até 15 pontos com rotação obrigatória a cada ponto ganho no saque, reforçando toda a lógica de rodízio em contexto de jogo real.",
        coachingPoints: ["Confirmar a rotação a cada troca de saque", "Manter a organização tática combinada"],
        technicalActions: { offensive: ["Sistema de ataque"], defensive: ["Sistema defensivo"] },
        tacticalPrinciple: "Consolidação do sistema completo",
        variants: { harder: "Jogar até 21 pontos", easier: "Jogar até 11 pontos com pausas para correção" },
        diagram: {
          players: [
            { x: 20, y: 85, team: "A", number: 1 },
            { x: 50, y: 90, team: "A", number: 6 },
            { x: 80, y: 85, team: "A", number: 5 },
            { x: 20, y: 15, team: "B", number: 4 },
            { x: 50, y: 10, team: "B", number: 3 },
            { x: 80, y: 15, team: "B", number: 2 },
          ],
          arrows: [],
          cones: [],
          balls: [{ x: 50, y: 50 }],
        },
      },
    ],
  },
  {
    slug: "precisao-do-libero",
    category: "Sub-17",
    hook: "A recepção quebra o ritmo de ataque do seu time?",
    title: "Precisão do Líbero",
    subtitle: "Recepção e passe de qualidade",
    objective: "Elevar a qualidade da recepção para permitir mais opções de ataque ao levantador.",
    courtSetup: "Quadra completa",
    totalDurationMin: 60,
    playersCount: 10,
    intensity: 2,
    materials: ["6 bolas", "1 alvo (arco ou bambolê)"],
    coverFrom: "#F59E0B",
    coverTo: "#B45309",
    blocks: [
      {
        order: 1,
        title: "Recepção no alvo",
        durationMin: 20,
        description: "Um treinador saca e o recebedor tenta direcionar a bola para dentro de um alvo posicionado perto da rede, simulando a zona ideal de levantamento.",
        coachingPoints: ["Plataforma de braços estável e direcionada ao alvo", "Pernas absorvem o impacto, não os braços"],
        technicalActions: { offensive: [], defensive: ["Recepção de saque"] },
        tacticalPrinciple: "Precisão como prioridade sobre velocidade",
        variants: { harder: "Reduzir o tamanho do alvo", easier: "Aumentar o alvo e reduzir a potência do saque" },
        diagram: {
          players: [{ x: 50, y: 80, team: "A", number: 8 }],
          arrows: [{ from: { x: 50, y: 15 }, to: { x: 50, y: 80 }, type: "serve", order: 1 }],
          cones: [{ x: 40, y: 40 }],
          balls: [{ x: 50, y: 15 }],
        },
      },
      {
        order: 2,
        title: "Recepção com múltiplos servidores",
        durationMin: 20,
        description: "Dois ou três atletas sacam alternadamente de posições diferentes, obrigando o líbero a ler ângulos variados de recepção.",
        coachingPoints: ["Reposicionar rapidamente entre recepções", "Comunicação para definir quem recebe"],
        technicalActions: { offensive: [], defensive: ["Recepção variada"] },
        tacticalPrinciple: "Adaptação a diferentes ângulos de saque",
        variants: { harder: "Adicionar saques flutuantes e com efeito", easier: "Manter todos os saques do mesmo ângulo" },
        diagram: {
          players: [
            { x: 40, y: 80, team: "A", number: 8 },
            { x: 20, y: 15, team: "B", number: 1 },
            { x: 80, y: 15, team: "B", number: 2 },
          ],
          arrows: [
            { from: { x: 20, y: 15 }, to: { x: 40, y: 80 }, type: "serve", order: 1 },
            { from: { x: 80, y: 15 }, to: { x: 40, y: 80 }, type: "serve", order: 2 },
          ],
          cones: [],
          balls: [{ x: 20, y: 15 }],
        },
      },
      {
        order: 3,
        title: "Recepção + ataque completo",
        durationMin: 20,
        description: "Sequência completa: saque, recepção do líbero, levantamento e ataque, fechando o ciclo e mostrando o impacto direto da recepção de qualidade.",
        coachingPoints: ["Ligar mentalmente recepção e ataque como uma sequência só", "Levantador se ajusta à qualidade da recepção"],
        technicalActions: { offensive: ["Ataque após recepção"], defensive: ["Recepção de saque"] },
        tacticalPrinciple: "Conexão entre recepção e eficiência ofensiva",
        variants: { harder: "Adicionar bloqueio simples no ataque final", easier: "Fixar sempre o mesmo tipo de levantamento após a recepção" },
        diagram: {
          players: [
            { x: 40, y: 80, team: "A", number: 8 },
            { x: 60, y: 60, team: "A", number: 3 },
            { x: 25, y: 40, team: "A", number: 9 },
            { x: 20, y: 15, team: "B", number: 1 },
          ],
          arrows: [
            { from: { x: 20, y: 15 }, to: { x: 40, y: 80 }, type: "serve", order: 1 },
            { from: { x: 40, y: 80 }, to: { x: 60, y: 60 }, type: "dig", order: 2 },
            { from: { x: 60, y: 60 }, to: { x: 25, y: 45 }, type: "set", order: 3 },
            { from: { x: 25, y: 45 }, to: { x: 25, y: 15 }, type: "spike", order: 4 },
          ],
          cones: [],
          balls: [{ x: 20, y: 15 }],
        },
      },
    ],
  },
  {
    slug: "pronto-pro-jogo",
    category: "Sênior",
    hook: "Seu time trava quando o jogo aperta?",
    title: "Pronto Pro Jogo",
    subtitle: "Simulado de jogo sob pressão",
    objective: "Simular situações de pressão de final de set para melhorar a resposta emocional e tática do time.",
    courtSetup: "Quadra completa",
    totalDurationMin: 70,
    playersCount: 12,
    intensity: 3,
    materials: ["6 bolas", "placar"],
    coverFrom: "#F43F5E",
    coverTo: "#9F1239",
    blocks: [
      {
        order: 1,
        title: "Ativação + saques de pressão",
        durationMin: 15,
        description: "Aquecimento seguido de série de saques em que cada erro soma ponto para o time adversário simbólico, criando leve pressão desde o início.",
        coachingPoints: ["Manter a rotina de saque mesmo sob pressão simulada", "Respiração controlada antes de cada saque"],
        technicalActions: { offensive: ["Saque sob pressão"], defensive: [] },
        tacticalPrinciple: "Preparação mental para pressão",
        variants: { harder: "Anunciar publicamente o placar a cada erro", easier: "Reduzir o número de saques na série" },
        diagram: {
          players: [{ x: 50, y: 92, team: "A", number: 7 }],
          arrows: [{ from: { x: 50, y: 92 }, to: { x: 50, y: 20 }, type: "serve", order: 1 }],
          cones: [],
          balls: [{ x: 50, y: 92 }],
        },
      },
      {
        order: 2,
        title: "Jogo iniciando em 22-24",
        durationMin: 30,
        description: "Sets simulados sempre começando com o placar 22x24 contra o time, obrigando a jogar pontos decisivos repetidamente na sessão.",
        coachingPoints: ["Comunicação verbal constante nos pontos decisivos", "Manter o sistema tático mesmo sob pressão"],
        technicalActions: { offensive: ["Sistema de ataque"], defensive: ["Sistema defensivo"] },
        tacticalPrinciple: "Exposição repetida a situações de pressão",
        variants: { harder: "Começar sempre 20-24", easier: "Começar em 22-22 (situação neutra de pressão)" },
        diagram: {
          players: [
            { x: 20, y: 85, team: "A", number: 1 },
            { x: 50, y: 90, team: "A", number: 6 },
            { x: 80, y: 85, team: "A", number: 5 },
            { x: 20, y: 15, team: "B", number: 4 },
            { x: 50, y: 10, team: "B", number: 3 },
            { x: 80, y: 15, team: "B", number: 2 },
          ],
          arrows: [],
          cones: [],
          balls: [{ x: 50, y: 50 }],
        },
      },
      {
        order: 3,
        title: "Roda de conversa tática",
        durationMin: 25,
        description: "Após os sets de pressão, o time se reúne para discutir decisões tomadas nos pontos decisivos e ajustar a comunicação para o próximo jogo.",
        coachingPoints: ["Focar em decisões, não em erros individuais", "Reforçar os pontos positivos observados"],
        technicalActions: { offensive: [], defensive: [] },
        tacticalPrinciple: "Consolidação mental e tática pós-simulado",
        variants: { harder: "Pedir que os próprios atletas liderem a análise", easier: "Treinador conduz toda a conversa" },
        diagram: {
          players: [
            { x: 30, y: 50, team: "A", number: 1 },
            { x: 45, y: 45, team: "A", number: 2 },
            { x: 60, y: 50, team: "A", number: 3 },
            { x: 45, y: 60, team: "A", number: 4 },
          ],
          arrows: [],
          cones: [],
          balls: [],
        },
      },
    ],
  },
];

export function getLibraryTemplate(slug: string) {
  return LIBRARY_TEMPLATES.find((t) => t.slug === slug) ?? null;
}
