export const LOCALES = ["pt", "en", "es", "fr", "it", "de"] as const;
export type Locale = (typeof LOCALES)[number];

export const LOCALE_LABELS: Record<Locale, string> = {
  pt: "Português",
  en: "English",
  es: "Español",
  fr: "Français",
  it: "Italiano",
  de: "Deutsch",
};

export type Dictionary = {
  common: {
    save: string; cancel: string; delete: string; edit: string; create: string; loading: string;
    back: string; next: string; search: string; remove: string; none: string; optional: string;
  };
  nav: {
    work: string; planning: string; account: string;
    dashboard: string; aiCoach: string; trainingBuilder: string; library: string; teams: string;
    players: string; calendar: string; season: string; favorites: string; history: string;
    profile: string; settings: string; signOut: string; role: string; support: string;
  };
  auth: {
    loginTitle: string; loginSubtitle: string; signupTitle: string; signupSubtitle: string;
    email: string; password: string; fullName: string; loginButton: string; signupButton: string;
    noAccount: string; haveAccount: string; loginLink: string; signupLink: string;
    loginError: string; signupError: string;
  };
  dashboard: {
    greeting: string; tagline: string; notifications: string; newTraining: string;
    metricTrainings: string; metricObjectives: string; metricPlayers: string; metricHours: string; thisMonth: string;
    quickCreateTitle: string; quickCreateSubtitle: string; category: string; objective: string;
    duration: string; players: string; quickCreateCta: string;
    aiTitle: string; aiDescription: string; aiCta: string;
    popularTitle: string; popularServe: string; popularAttack: string; popularBlock: string;
    popularSet: string; popularDig: string; popularReception: string; popularRotation: string; popularSmallSided: string;
    recentTitle: string; recentEmpty: string; recentEmptyCta: string;
    supportTitle: string; supportDesc: string; supportCta: string;
  };
  teams: {
    title: string; subtitle: string; newTeam: string; emptyTitle: string; emptyDesc: string;
    dialogCreateTitle: string; dialogEditTitle: string; dialogSubtitle: string;
    name: string; category: string; season: string; playSystem: string; priorities: string;
    playersCount: string; ready: string; deleteTitle: string; deleteConfirm: string;
    createButton: string; saveButton: string;
  };
  players: {
    title: string; subtitle: string; newPlayer: string; emptyTitleNoTeam: string; emptyDescNoTeam: string;
    emptyTitle: string; emptyDesc: string; addPlayer: string; name: string; team: string; position: string;
    birthDate: string; dialogCreateTitle: string; dialogEditTitle: string; dialogSubtitle: string;
    removeTitle: string; removeConfirm: string; saveButton: string; createButton: string;
  };
  trainingBuilder: {
    title: string; subtitle: string;
    stepCategory: string; stepObjective: string; stepContext: string; stepMaterials: string; stepReview: string;
    stepOf: string; categoryLabel: string; team: string; noTeam: string; objectiveLabel: string;
    objectivePlaceholder: string; playersLabel: string; durationLabel: string; courtLabel: string;
    weekMomentLabel: string; materialsLabel: string; materialsPlaceholder: string; notesLabel: string;
    notesPlaceholder: string; reviewTitle: string; reviewDesc: string; back: string; next: string;
    generate: string; generating: string;
    categoryU6: string; categoryU11: string; categoryU14: string; categoryU16: string; categoryPro: string;
    objectiveSuggestions: string[];
    courtReduced: string; courtAttack: string; courtHalf: string; courtFull: string;
    momentPreSeason: string; momentMidWeek: string; momentMatchWeek: string; momentPost: string;
  };
  aiCoach: {
    title: string; subtitle: string; conversations: string; newConversation: string; empty: string;
    placeholder: string; suggestionsLabel: string; deleteConfirm: string; noTeam: string;
    suggestion1: string; suggestion2: string; suggestion3: string; trainingReady: string;
  };
  trainingDoc: {
    category: string; duration: string; players: string; court: string; intensity: string; materials: string;
    blocks: string; coachingPoints: string; offensive: string; defensive: string; tacticalPrinciple: string;
    progressions: string; regressions: string; socioAffective: string; notes: string; print: string;
    favorite: string; favorited: string; howTo: string; step: string; setup: string; noDiagram: string;
  };
  history: { title: string; subtitle: string; empty: string };
  library: {
    title: string; subtitle: string; empty: string; useAsBase: string; searchPlaceholder: string; allCategories: string; readyMade: string; myTrainings: string; readyMadeBadge: string; useTraining: string; variants: string; harder: string; easier: string; usingTemplate: string; notFound: string; backToLibrary: string; useMessageUser: string; useMessageAssistant: string;
    filterAll: string; skillServe: string; skillPass: string; skillSet: string; skillAttack: string; skillBlock: string; skillDefense: string; skillLibero: string; skillRotation: string; skillCoverage: string; skillTransition: string; skillCommunication: string; skillSmallSided: string; skillConditioning: string; skillPressure: string; filterMore: string;
  };
  favorites: { title: string; subtitle: string; empty: string };
  calendar: { title: string; subtitle: string; schedule: string; scheduleTitle: string; date: string; empty: string; scheduled: string; remove: string };
  season: { title: string; subtitle: string; newPhase: string; phaseName: string; phaseColor: string; startDate: string; endDate: string; currentPhase: string; empty: string; deleteConfirm: string };
  profile: { title: string; subtitle: string; fullName: string; email: string; currentPassword: string; newPassword: string; save: string; saved: string; changePassword: string; wrongPassword: string; emailTaken: string; passwordSaved: string };
  settings: { title: string; subtitle: string; account: string; name: string; email: string; appearance: string; appearanceDesc: string; language: string };
  errors: { rateLimited: string; noCredits: string; aiError: string };
  purchase: { title: string; subtitle: string; emailLabel: string; emailPlaceholder: string; verifyButton: string; verifying: string; notFound: string; error: string; supportHint: string };
  tour: {
    bannerTitle: string; bannerDesc: string; start: string; stepOf: string; skip: string; back: string; next: string; finish: string;
    stepDashboardTitle: string; stepDashboardDesc: string;
    stepAiCoachTitle: string; stepAiCoachDesc: string;
    stepTrainingBuilderTitle: string; stepTrainingBuilderDesc: string;
    stepLibraryTitle: string; stepLibraryDesc: string;
    stepTeamsTitle: string; stepTeamsDesc: string;
    stepPlayersTitle: string; stepPlayersDesc: string;
    stepCalendarTitle: string; stepCalendarDesc: string;
    stepSeasonTitle: string; stepSeasonDesc: string;
  };
};

export const dictionaries: Record<Locale, Dictionary> = {
  pt: {
    common: { save: "Salvar", cancel: "Cancelar", delete: "Excluir", edit: "Editar", create: "Criar", loading: "Carregando...", back: "Voltar", next: "Próximo", search: "Buscar", remove: "Remover", none: "Nenhum", optional: "opcional" },
    nav: { work: "Trabalho", planning: "Planejamento", account: "Conta", dashboard: "Painel", aiCoach: "Assistente IA", trainingBuilder: "Criar treino", library: "Biblioteca", teams: "Times", players: "Jogadores", calendar: "Calendário", season: "Temporada", favorites: "Favoritos", history: "Histórico", profile: "Perfil", settings: "Configurações", signOut: "Sair", role: "Treinador(a)", support: "Suporte" },
    auth: { loginTitle: "Entrar", loginSubtitle: "Acesse seu painel de treinador.", signupTitle: "Criar conta", signupSubtitle: "Comece a planejar treinos com IA.", email: "E-mail", password: "Senha", fullName: "Nome completo", loginButton: "Entrar", signupButton: "Criar conta", noAccount: "Ainda não tem conta?", haveAccount: "Já tem conta?", loginLink: "Entrar", signupLink: "Criar conta", loginError: "Não foi possível entrar.", signupError: "Não foi possível criar sua conta." },
    dashboard: { greeting: "Olá", tagline: "Vamos planejar o próximo treino do seu time.", notifications: "Notificações", newTraining: "Novo treino", metricTrainings: "Treinos criados", metricObjectives: "Objetivos", metricPlayers: "Jogadores acompanhados", metricHours: "Horas economizadas", thisMonth: "este mês", quickCreateTitle: "Criação rápida", quickCreateSubtitle: "Monte um treino em segundos", category: "Categoria", objective: "Objetivo", duration: "Duração", players: "Jogadores", quickCreateCta: "Criar treino", aiTitle: "Assistente de IA", aiDescription: "Converse com o CoachAI para tirar dúvidas táticas, pedir ajustes num treino existente ou gerar um plano do zero, com diagramas de quadra prontos.", aiCta: "Abrir assistente", popularTitle: "Populares", popularServe: "Saque", popularAttack: "Ataque", popularBlock: "Bloqueio", popularSet: "Levantamento", popularDig: "Defesa", popularReception: "Recepção", popularRotation: "Rodízio tático", popularSmallSided: "Jogos reduzidos", recentTitle: "Treinos recentes", recentEmpty: "Você ainda não criou nenhum treino.", recentEmptyCta: "Criar meu primeiro treino", supportTitle: "Precisa de ajuda?", supportDesc: "Fale com a gente por e-mail e responderemos suas dúvidas o quanto antes.", supportCta: "Enviar e-mail" },
    teams: { title: "Times", subtitle: "Organize seus times, sistemas de jogo e prioridades da temporada.", newTeam: "Novo time", emptyTitle: "Nenhum time cadastrado", emptyDesc: "Crie seu primeiro time para começar a planejar treinos personalizados.", dialogCreateTitle: "Novo time", dialogEditTitle: "Editar time", dialogSubtitle: "Defina a identidade e o sistema de jogo do time.", name: "Nome do time", category: "Categoria", season: "Temporada", playSystem: "Sistema de jogo", priorities: "Prioridades da temporada", playersCount: "jogadores", ready: "pronto", deleteTitle: "Excluir time", deleteConfirm: "Tem certeza que deseja excluir esse time? Os jogadores vinculados também serão removidos. Essa ação não pode ser desfeita.", createButton: "Criar time", saveButton: "Salvar alterações" },
    players: { title: "Jogadores", subtitle: "Acompanhe o elenco de cada time.", newPlayer: "Novo jogador", emptyTitleNoTeam: "Crie um time primeiro", emptyDescNoTeam: "Você precisa de pelo menos um time antes de cadastrar jogadores.", emptyTitle: "Nenhum jogador cadastrado", emptyDesc: "Adicione jogadores para acompanhar o desenvolvimento de cada um.", addPlayer: "Adicionar jogador", name: "Nome", team: "Time", position: "Posição", birthDate: "Nascimento", dialogCreateTitle: "Novo jogador", dialogEditTitle: "Editar jogador", dialogSubtitle: "Informações básicas do atleta.", removeTitle: "Remover jogador", removeConfirm: "Tem certeza que deseja remover esse jogador?", saveButton: "Salvar alterações", createButton: "Adicionar" },
    trainingBuilder: { title: "Criar treino", subtitle: "Responda algumas perguntas e o CoachAI monta o plano completo com diagramas.", stepCategory: "Categoria", stepObjective: "Objetivo", stepContext: "Contexto", stepMaterials: "Materiais", stepReview: "Revisão", stepOf: "Passo {n} de {total}", categoryLabel: "Categoria", team: "Time", noTeam: "Nenhum time específico", objectiveLabel: "Objetivo do treino", objectivePlaceholder: "Descreva o objetivo principal do treino...", playersLabel: "Número de jogadores", durationLabel: "Duração (min)", courtLabel: "Quadra", weekMomentLabel: "Momento da semana", materialsLabel: "Materiais disponíveis", materialsPlaceholder: "Ex: 12 coletes, 20 cones, 6 bolas...", notesLabel: "Observações", notesPlaceholder: "Alguma restrição, lesão, foco especial...", reviewTitle: "Revisão", reviewDesc: "Confira os dados antes de gerar o treino com IA.", back: "Voltar", next: "Próximo", generate: "Gerar treino", generating: "Gerando treino...", categoryU6: "Sub-6 (iniciação)", categoryU11: "Sub-11", categoryU14: "Sub-14", categoryU16: "Sub-16", categoryPro: "Profissional", objectiveSuggestions: ["Recepção de saque", "Ataque de posição 4", "Bloqueio duplo", "Levantamento e distribuição", "Defesa de quadra", "Saque flutuante"], courtReduced: "Quadra reduzida", courtAttack: "Zona de ataque", courtHalf: "Meia quadra", courtFull: "Quadra completa", momentPreSeason: "Pré-temporada", momentMidWeek: "Meio de semana", momentMatchWeek: "Semana de jogo", momentPost: "Pós-jogo", },
    aiCoach: { title: "CoachAI", subtitle: "Seu assistente tático", conversations: "Conversas", newConversation: "Nova conversa", empty: "Nenhuma conversa ainda.", placeholder: "Escreva sua mensagem...", suggestionsLabel: "Sugestões", deleteConfirm: "Excluir esta conversa?", noTeam: "Nenhum time", suggestion1: "Monte um treino de ataque de posição 4 para sub-14, 60 minutos", suggestion2: "Como melhorar o bloqueio duplo do meu time?", suggestion3: "Preciso de um aquecimento de 15 minutos para pré-temporada", trainingReady: 'Prontinho! Preparei "{title}" com {blocks} blocos e {duration} minutos. Dá uma olhada no plano completo abaixo.' },
    trainingDoc: { category: "Categoria", duration: "Duração", players: "Jogadores", court: "Quadra", intensity: "Intensidade", materials: "Materiais", blocks: "Blocos do treino", coachingPoints: "Pontos de coaching", offensive: "Ofensivo", defensive: "Defensivo", tacticalPrinciple: "Princípio tático", progressions: "Progressões", regressions: "Regressões", socioAffective: "Socioafetivo", notes: "Notas", print: "Imprimir", favorite: "Favoritar", favorited: "Favoritado", howTo: "Como executar", step: "Passo", setup: "Contexto do exercício", noDiagram: "Diagrama detalhado em breve para este bloco." },
    history: { title: "Histórico", subtitle: "Todos os treinos que você já gerou.", empty: "Nenhum treino no histórico ainda." },
    library: { title: "Biblioteca", subtitle: "Sessões prontas e os treinos que você já gerou.", empty: "Nenhum treino na biblioteca ainda.", useAsBase: "Usar como base", searchPlaceholder: "Buscar por título ou objetivo...", allCategories: "Todas as categorias", readyMade: "Sessões prontas", myTrainings: "Meus treinos", readyMadeBadge: "Sessão pronta", useTraining: "Usar este treino", variants: "Variações", harder: "Mais difícil", easier: "Mais fácil", usingTemplate: "Preparando seu treino...", notFound: "Treino não encontrado.", backToLibrary: "Voltar para a biblioteca", useMessageUser: 'Quero usar a sessão pronta "{title}" ({category}).', useMessageAssistant: 'Prontinho! Carreguei "{title}" com {blocks} blocos e {duration} minutos. Dá uma olhada no plano completo abaixo.' , filterAll: "Todos", skillServe: "Saque", skillPass: "Recepção", skillSet: "Levantamento", skillAttack: "Ataque", skillBlock: "Bloqueio", skillDefense: "Defesa", skillLibero: "Líbero", skillRotation: "Rodízio", skillCoverage: "Cobertura", skillTransition: "Transição", skillCommunication: "Comunicação", skillSmallSided: "Jogo reduzido", skillConditioning: "Condicionamento", skillPressure: "Pressão", filterMore: "Mais" },
    favorites: { title: "Favoritos", subtitle: "Seus treinos marcados como favoritos.", empty: "Você ainda não favoritou nenhum treino." },
    calendar: { title: "Calendário", subtitle: "Agende seus treinos por data.", schedule: "Agendar", scheduleTitle: "Agendar treino", date: "Data", empty: "Nenhum treino agendado para este dia.", scheduled: "Treinos agendados", remove: "Remover" },
    season: { title: "Temporada", subtitle: "Defina as fases da temporada de cada time.", newPhase: "Nova fase", phaseName: "Nome da fase", phaseColor: "Cor", startDate: "Início", endDate: "Fim", currentPhase: "Fase atual", empty: "Nenhuma fase cadastrada ainda.", deleteConfirm: "Remover esta fase?" },
    profile: { title: "Perfil", subtitle: "Edite os dados da sua conta.", fullName: "Nome completo", email: "E-mail", currentPassword: "Senha atual", newPassword: "Nova senha", save: "Salvar alterações", saved: "Perfil atualizado.", changePassword: "Alterar senha", wrongPassword: "Senha atual incorreta.", emailTaken: "Esse e-mail já está em uso.", passwordSaved: "Senha alterada." },
    settings: { title: "Configurações", subtitle: "Preferências da sua conta.", account: "Conta", name: "Nome", email: "E-mail", appearance: "Aparência", appearanceDesc: "Alterne entre tema claro e escuro.", language: "Idioma" },
    errors: { rateLimited: "Muitas requisições agora. Tente novamente em instantes.", noCredits: "A chave da OpenAI não está configurada ou sem créditos. Verifique a variável OPENAI_KEY.", aiError: "Não foi possível processar agora. Tente novamente." },
    purchase: { title: "Confirme sua compra", subtitle: "Digite o e-mail usado na compra do CoachAI Vôlei na Hotmart para continuar.", emailLabel: "E-mail da compra", emailPlaceholder: "seuemail@exemplo.com", verifyButton: "Verificar e continuar", verifying: "Verificando...", notFound: "Não encontramos uma compra aprovada com esse e-mail.", error: "Não foi possível verificar agora. Tente novamente em instantes.", supportHint: "Comprou e o e-mail não bate? Fale com o suporte." },
    tour: { bannerTitle: "Conheça o CoachAI em 2 minutos", bannerDesc: "Um tour rápido pelo essencial.", start: "Começar", stepOf: "Passo {n} de {total}", skip: "Pular tutorial", back: "Voltar", next: "Próximo", finish: "Concluir", stepDashboardTitle: "Painel", stepDashboardDesc: "Aqui você vê um resumo do seu trabalho: treinos criados, jogadores acompanhados e os treinos mais recentes.", stepAiCoachTitle: "Assistente IA", stepAiCoachDesc: "Seu treinador assistente. Descreva o grupo, o tempo e o objetivo — receba uma sessão completa com blocos, tempos e pontos de coaching.", stepTrainingBuilderTitle: "Criar treino", stepTrainingBuilderDesc: "Monte um treino passo a passo respondendo perguntas simples, e deixe a IA gerar o plano completo com diagramas.", stepLibraryTitle: "Biblioteca", stepLibraryDesc: "Sessões prontas organizadas por tipo de habilidade — saque, ataque, bloqueio e muito mais — prontas para usar ou adaptar.", stepTeamsTitle: "Times", stepTeamsDesc: "Cadastre seus times, defina o sistema de jogo e as prioridades da temporada.", stepPlayersTitle: "Jogadores", stepPlayersDesc: "Acompanhe o elenco de cada time e o desenvolvimento individual dos atletas.", stepCalendarTitle: "Calendário", stepCalendarDesc: "Agende seus treinos por data e tenha uma visão semanal do planejamento.", stepSeasonTitle: "Temporada", stepSeasonDesc: "Divida a temporada em fases e acompanhe em qual momento do ciclo seu time está." },
  },
  en: {
    common: { save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", create: "Create", loading: "Loading...", back: "Back", next: "Next", search: "Search", remove: "Remove", none: "None", optional: "optional" },
    nav: { work: "Work", planning: "Planning", account: "Account", dashboard: "Dashboard", aiCoach: "AI Coach", trainingBuilder: "Training builder", library: "Library", teams: "Teams", players: "Players", calendar: "Calendar", season: "Season", favorites: "Favorites", history: "History", profile: "Profile", settings: "Settings", signOut: "Sign out", role: "Coach", support: "Support" },
    auth: { loginTitle: "Sign in", loginSubtitle: "Access your coaching dashboard.", signupTitle: "Create account", signupSubtitle: "Start planning trainings with AI.", email: "Email", password: "Password", fullName: "Full name", loginButton: "Sign in", signupButton: "Create account", noAccount: "Don't have an account?", haveAccount: "Already have an account?", loginLink: "Sign in", signupLink: "Create account", loginError: "Could not sign in.", signupError: "Could not create your account." },
    dashboard: { greeting: "Hi", tagline: "Let's plan your team's next training.", notifications: "Notifications", newTraining: "New training", metricTrainings: "Trainings created", metricObjectives: "Objectives", metricPlayers: "Players followed", metricHours: "Hours saved", thisMonth: "this month", quickCreateTitle: "Quick create", quickCreateSubtitle: "Build a training in seconds", category: "Category", objective: "Objective", duration: "Duration", players: "Players", quickCreateCta: "Create training", aiTitle: "AI Assistant", aiDescription: "Chat with CoachAI to clear up tactical doubts, tweak an existing training, or generate a plan from scratch, with ready-made court diagrams.", aiCta: "Open assistant", popularTitle: "Popular", popularServe: "Serve", popularAttack: "Attack", popularBlock: "Block", popularSet: "Set", popularDig: "Dig", popularReception: "Reception", popularRotation: "Rotation", popularSmallSided: "Small-sided games", recentTitle: "Recent trainings", recentEmpty: "You haven't created any trainings yet.", recentEmptyCta: "Create my first training", supportTitle: "Need help?", supportDesc: "Email us and we'll get back to your questions as soon as possible.", supportCta: "Send email" },
    teams: { title: "Teams", subtitle: "Organize your teams, play systems, and season priorities.", newTeam: "New team", emptyTitle: "No teams yet", emptyDesc: "Create your first team to start planning personalized trainings.", dialogCreateTitle: "New team", dialogEditTitle: "Edit team", dialogSubtitle: "Set the team's identity and play system.", name: "Team name", category: "Category", season: "Season", playSystem: "Play system", priorities: "Season priorities", playersCount: "players", ready: "ready", deleteTitle: "Delete team", deleteConfirm: "Are you sure you want to delete this team? Linked players will also be removed. This can't be undone.", createButton: "Create team", saveButton: "Save changes" },
    players: { title: "Players", subtitle: "Track each team's roster.", newPlayer: "New player", emptyTitleNoTeam: "Create a team first", emptyDescNoTeam: "You need at least one team before adding players.", emptyTitle: "No players yet", emptyDesc: "Add players to track each one's development.", addPlayer: "Add player", name: "Name", team: "Team", position: "Position", birthDate: "Birth date", dialogCreateTitle: "New player", dialogEditTitle: "Edit player", dialogSubtitle: "Basic athlete information.", removeTitle: "Remove player", removeConfirm: "Are you sure you want to remove this player?", saveButton: "Save changes", createButton: "Add" },
    trainingBuilder: { title: "Create training", subtitle: "Answer a few questions and CoachAI builds the full plan with diagrams.", stepCategory: "Category", stepObjective: "Objective", stepContext: "Context", stepMaterials: "Materials", stepReview: "Review", stepOf: "Step {n} of {total}", categoryLabel: "Category", team: "Team", noTeam: "No specific team", objectiveLabel: "Training objective", objectivePlaceholder: "Describe the main objective of the training...", playersLabel: "Number of players", durationLabel: "Duration (min)", courtLabel: "Court", weekMomentLabel: "Moment of the week", materialsLabel: "Available materials", materialsPlaceholder: "E.g.: 12 bibs, 20 cones, 6 balls...", notesLabel: "Notes", notesPlaceholder: "Any restriction, injury, special focus...", reviewTitle: "Review", reviewDesc: "Check the details before generating the training with AI.", back: "Back", next: "Next", generate: "Generate training", generating: "Generating training...", categoryU6: "U6 (introductory)", categoryU11: "U11", categoryU14: "U14", categoryU16: "U16", categoryPro: "Professional", objectiveSuggestions: ["Serve reception", "Position 4 attack", "Double block", "Setting and distribution", "Floor defense", "Floater serve"], courtReduced: "Reduced court", courtAttack: "Attack zone", courtHalf: "Half court", courtFull: "Full court", momentPreSeason: "Pre-season", momentMidWeek: "Midweek", momentMatchWeek: "Match week", momentPost: "Post-match", },
    aiCoach: { title: "CoachAI", subtitle: "Your tactical assistant", conversations: "Conversations", newConversation: "New conversation", empty: "No conversations yet.", placeholder: "Write your message...", suggestionsLabel: "Suggestions", deleteConfirm: "Delete this conversation?", noTeam: "No team", suggestion1: "Build a position-4 attack training for U14, 60 minutes", suggestion2: "How can I improve my team's double block?", suggestion3: "I need a 15-minute warm-up for pre-season", trainingReady: 'All set! I put together "{title}" with {blocks} blocks and {duration} minutes. Check out the full plan below.' },
    trainingDoc: { category: "Category", duration: "Duration", players: "Players", court: "Court", intensity: "Intensity", materials: "Materials", blocks: "Training blocks", coachingPoints: "Coaching points", offensive: "Offensive", defensive: "Defensive", tacticalPrinciple: "Tactical principle", progressions: "Progressions", regressions: "Regressions", socioAffective: "Social/affective", notes: "Notes", print: "Print", favorite: "Favorite", favorited: "Favorited", howTo: "How to run it", step: "Step", setup: "Exercise setup", noDiagram: "Detailed diagram coming soon for this block." },
    history: { title: "History", subtitle: "All the trainings you've generated.", empty: "No trainings in the history yet." },
    library: { title: "Library", subtitle: "Ready-made sessions and the trainings you've generated.", empty: "No trainings in the library yet.", useAsBase: "Use as base", searchPlaceholder: "Search by title or objective...", allCategories: "All categories", readyMade: "Ready-made sessions", myTrainings: "My trainings", readyMadeBadge: "Ready-made session", useTraining: "Use this training", variants: "Variants", harder: "Harder", easier: "Easier", usingTemplate: "Preparing your training...", notFound: "Training not found.", backToLibrary: "Back to library", useMessageUser: 'I want to use the ready-made session "{title}" ({category}).', useMessageAssistant: 'All set! I loaded "{title}" with {blocks} blocks and {duration} minutes. Check out the full plan below.' , filterAll: "All", skillServe: "Serving", skillPass: "Passing", skillSet: "Setting", skillAttack: "Attacking", skillBlock: "Blocking", skillDefense: "Defense", skillLibero: "Libero", skillRotation: "Rotation", skillCoverage: "Coverage", skillTransition: "Transition", skillCommunication: "Communication", skillSmallSided: "Game-like", skillConditioning: "Conditioning", skillPressure: "Pressure", filterMore: "More" },
    favorites: { title: "Favorites", subtitle: "Your trainings marked as favorites.", empty: "You haven't favorited any trainings yet." },
    calendar: { title: "Calendar", subtitle: "Schedule your trainings by date.", schedule: "Schedule", scheduleTitle: "Schedule training", date: "Date", empty: "No trainings scheduled for this day.", scheduled: "Scheduled trainings", remove: "Remove" },
    season: { title: "Season", subtitle: "Define each team's season phases.", newPhase: "New phase", phaseName: "Phase name", phaseColor: "Color", startDate: "Start", endDate: "End", currentPhase: "Current phase", empty: "No phases yet.", deleteConfirm: "Remove this phase?" },
    profile: { title: "Profile", subtitle: "Edit your account details.", fullName: "Full name", email: "Email", currentPassword: "Current password", newPassword: "New password", save: "Save changes", saved: "Profile updated.", changePassword: "Change password", wrongPassword: "Current password is incorrect.", emailTaken: "This email is already in use.", passwordSaved: "Password changed." },
    settings: { title: "Settings", subtitle: "Your account preferences.", account: "Account", name: "Name", email: "Email", appearance: "Appearance", appearanceDesc: "Switch between light and dark theme.", language: "Language" },
    errors: { rateLimited: "Too many requests right now. Try again shortly.", noCredits: "The OpenAI key isn't configured or is out of credits. Check the OPENAI_KEY variable.", aiError: "Couldn't process this right now. Try again." },
    purchase: { title: "Confirm your purchase", subtitle: "Enter the email you used to buy CoachAI Vôlei on Hotmart to continue.", emailLabel: "Purchase email", emailPlaceholder: "youremail@example.com", verifyButton: "Verify and continue", verifying: "Verifying...", notFound: "We couldn't find an approved purchase with that email.", error: "Couldn't verify right now. Try again shortly.", supportHint: "Bought it but the email doesn't match? Contact support." },
    tour: { bannerTitle: "Discover CoachAI in 2 minutes", bannerDesc: "A quick tour through the essentials.", start: "Start", stepOf: "Step {n} of {total}", skip: "Skip tutorial", back: "Back", next: "Next", finish: "Finish", stepDashboardTitle: "Dashboard", stepDashboardDesc: "See a summary of your work here: trainings created, players followed, and your most recent trainings.", stepAiCoachTitle: "AI Coach", stepAiCoachDesc: "Your assistant coach. Describe the group, the time and the goal — get a full session with blocks, timings and coaching points.", stepTrainingBuilderTitle: "Training builder", stepTrainingBuilderDesc: "Build a training step by step by answering simple questions, and let the AI generate the full plan with diagrams.", stepLibraryTitle: "Library", stepLibraryDesc: "Ready-made sessions organized by skill type — serving, attacking, blocking and more — ready to use or adapt.", stepTeamsTitle: "Teams", stepTeamsDesc: "Register your teams, set the play system and the season's priorities.", stepPlayersTitle: "Players", stepPlayersDesc: "Track each team's roster and every athlete's individual development.", stepCalendarTitle: "Calendar", stepCalendarDesc: "Schedule your trainings by date and get a weekly view of your planning.", stepSeasonTitle: "Season", stepSeasonDesc: "Split the season into phases and track which stage of the cycle your team is in." },
  },
  es: {
    common: { save: "Guardar", cancel: "Cancelar", delete: "Eliminar", edit: "Editar", create: "Crear", loading: "Cargando...", back: "Volver", next: "Siguiente", search: "Buscar", remove: "Quitar", none: "Ninguno", optional: "opcional" },
    nav: { work: "Trabajo", planning: "Planificación", account: "Cuenta", dashboard: "Panel", aiCoach: "Asistente IA", trainingBuilder: "Crear entrenamiento", library: "Biblioteca", teams: "Equipos", players: "Jugadores", calendar: "Calendario", season: "Temporada", favorites: "Favoritos", history: "Historial", profile: "Perfil", settings: "Configuración", signOut: "Cerrar sesión", role: "Entrenador/a", support: "Soporte" },
    auth: { loginTitle: "Iniciar sesión", loginSubtitle: "Accede a tu panel de entrenador.", signupTitle: "Crear cuenta", signupSubtitle: "Empieza a planificar entrenamientos con IA.", email: "Correo electrónico", password: "Contraseña", fullName: "Nombre completo", loginButton: "Iniciar sesión", signupButton: "Crear cuenta", noAccount: "¿Aún no tienes cuenta?", haveAccount: "¿Ya tienes cuenta?", loginLink: "Iniciar sesión", signupLink: "Crear cuenta", loginError: "No fue posible iniciar sesión.", signupError: "No fue posible crear tu cuenta." },
    dashboard: { greeting: "Hola", tagline: "Vamos a planificar el próximo entrenamiento de tu equipo.", notifications: "Notificaciones", newTraining: "Nuevo entrenamiento", metricTrainings: "Entrenamientos creados", metricObjectives: "Objetivos", metricPlayers: "Jugadores seguidos", metricHours: "Horas ahorradas", thisMonth: "este mes", quickCreateTitle: "Creación rápida", quickCreateSubtitle: "Crea un entrenamiento en segundos", category: "Categoría", objective: "Objetivo", duration: "Duración", players: "Jugadores", quickCreateCta: "Crear entrenamiento", aiTitle: "Asistente de IA", aiDescription: "Conversa con CoachAI para resolver dudas tácticas, ajustar un entrenamiento existente o generar un plan desde cero, con diagramas de cancha listos.", aiCta: "Abrir asistente", popularTitle: "Populares", popularServe: "Saque", popularAttack: "Ataque", popularBlock: "Bloqueo", popularSet: "Colocación", popularDig: "Defensa", popularReception: "Recepción", popularRotation: "Rotación táctica", popularSmallSided: "Juegos reducidos", recentTitle: "Entrenamientos recientes", recentEmpty: "Aún no has creado ningún entrenamiento.", recentEmptyCta: "Crear mi primer entrenamiento", supportTitle: "¿Necesitas ayuda?", supportDesc: "Escríbenos por correo y responderemos tus dudas lo antes posible.", supportCta: "Enviar correo" },
    teams: { title: "Equipos", subtitle: "Organiza tus equipos, sistemas de juego y prioridades de la temporada.", newTeam: "Nuevo equipo", emptyTitle: "Aún no hay equipos", emptyDesc: "Crea tu primer equipo para empezar a planificar entrenamientos personalizados.", dialogCreateTitle: "Nuevo equipo", dialogEditTitle: "Editar equipo", dialogSubtitle: "Define la identidad y el sistema de juego del equipo.", name: "Nombre del equipo", category: "Categoría", season: "Temporada", playSystem: "Sistema de juego", priorities: "Prioridades de la temporada", playersCount: "jugadores", ready: "listo", deleteTitle: "Eliminar equipo", deleteConfirm: "¿Seguro que quieres eliminar este equipo? Los jugadores vinculados también se eliminarán. Esta acción no se puede deshacer.", createButton: "Crear equipo", saveButton: "Guardar cambios" },
    players: { title: "Jugadores", subtitle: "Sigue la plantilla de cada equipo.", newPlayer: "Nuevo jugador", emptyTitleNoTeam: "Crea un equipo primero", emptyDescNoTeam: "Necesitas al menos un equipo antes de agregar jugadores.", emptyTitle: "Aún no hay jugadores", emptyDesc: "Agrega jugadores para seguir el desarrollo de cada uno.", addPlayer: "Agregar jugador", name: "Nombre", team: "Equipo", position: "Posición", birthDate: "Nacimiento", dialogCreateTitle: "Nuevo jugador", dialogEditTitle: "Editar jugador", dialogSubtitle: "Información básica del atleta.", removeTitle: "Quitar jugador", removeConfirm: "¿Seguro que quieres quitar este jugador?", saveButton: "Guardar cambios", createButton: "Agregar" },
    trainingBuilder: { title: "Crear entrenamiento", subtitle: "Responde algunas preguntas y CoachAI arma el plan completo con diagramas.", stepCategory: "Categoría", stepObjective: "Objetivo", stepContext: "Contexto", stepMaterials: "Materiales", stepReview: "Revisión", stepOf: "Paso {n} de {total}", categoryLabel: "Categoría", team: "Equipo", noTeam: "Ningún equipo específico", objectiveLabel: "Objetivo del entrenamiento", objectivePlaceholder: "Describe el objetivo principal del entrenamiento...", playersLabel: "Número de jugadores", durationLabel: "Duración (min)", courtLabel: "Cancha", weekMomentLabel: "Momento de la semana", materialsLabel: "Materiales disponibles", materialsPlaceholder: "Ej: 12 petos, 20 conos, 6 balones...", notesLabel: "Observaciones", notesPlaceholder: "Alguna restricción, lesión, enfoque especial...", reviewTitle: "Revisión", reviewDesc: "Revisa los datos antes de generar el entrenamiento con IA.", back: "Volver", next: "Siguiente", generate: "Generar entrenamiento", generating: "Generando entrenamiento...", categoryU6: "Sub-6 (iniciación)", categoryU11: "Sub-11", categoryU14: "Sub-14", categoryU16: "Sub-16", categoryPro: "Profesional", objectiveSuggestions: ["Recepción de saque", "Ataque de posición 4", "Bloqueo doble", "Colocación y distribución", "Defensa de cancha", "Saque flotante"], courtReduced: "Cancha reducida", courtAttack: "Zona de ataque", courtHalf: "Media cancha", courtFull: "Cancha completa", momentPreSeason: "Pretemporada", momentMidWeek: "Entre semana", momentMatchWeek: "Semana de partido", momentPost: "Post-partido", },
    aiCoach: { title: "CoachAI", subtitle: "Tu asistente táctico", conversations: "Conversaciones", newConversation: "Nueva conversación", empty: "Aún no hay conversaciones.", placeholder: "Escribe tu mensaje...", suggestionsLabel: "Sugerencias", deleteConfirm: "¿Eliminar esta conversación?", noTeam: "Ningún equipo", suggestion1: "Arma un entrenamiento de ataque de posición 4 para sub-14, 60 minutos", suggestion2: "¿Cómo mejoro el bloqueo doble de mi equipo?", suggestion3: "Necesito un calentamiento de 15 minutos para la pretemporada", trainingReady: '¡Listo! Preparé "{title}" con {blocks} bloques y {duration} minutos. Échale un vistazo al plan completo abajo.' },
    trainingDoc: { category: "Categoría", duration: "Duración", players: "Jugadores", court: "Cancha", intensity: "Intensidad", materials: "Materiales", blocks: "Bloques del entrenamiento", coachingPoints: "Puntos de coaching", offensive: "Ofensivo", defensive: "Defensivo", tacticalPrinciple: "Principio táctico", progressions: "Progresiones", regressions: "Regresiones", socioAffective: "Socioafectivo", notes: "Notas", print: "Imprimir", favorite: "Favorito", favorited: "Favorito", howTo: "Cómo ejecutarlo", step: "Paso", setup: "Contexto del ejercicio", noDiagram: "Diagrama detallado próximamente para este bloque." },
    history: { title: "Historial", subtitle: "Todos los entrenamientos que has generado.", empty: "Aún no hay entrenamientos en el historial." },
    library: { title: "Biblioteca", subtitle: "Sesiones listas y los entrenamientos que ya generaste.", empty: "Aún no hay entrenamientos en la biblioteca.", useAsBase: "Usar como base", searchPlaceholder: "Buscar por título u objetivo...", allCategories: "Todas las categorías", readyMade: "Sesiones listas", myTrainings: "Mis entrenamientos", readyMadeBadge: "Sesión lista", useTraining: "Usar este entrenamiento", variants: "Variantes", harder: "Más difícil", easier: "Más fácil", usingTemplate: "Preparando tu entrenamiento...", notFound: "Entrenamiento no encontrado.", backToLibrary: "Volver a la biblioteca", useMessageUser: 'Quiero usar la sesión lista "{title}" ({category}).', useMessageAssistant: '¡Listo! Cargué "{title}" con {blocks} bloques y {duration} minutos. Échale un vistazo al plan completo abajo.' , filterAll: "Todos", skillServe: "Saque", skillPass: "Recepción", skillSet: "Colocación", skillAttack: "Ataque", skillBlock: "Bloqueo", skillDefense: "Defensa", skillLibero: "Líbero", skillRotation: "Rotación", skillCoverage: "Cobertura", skillTransition: "Transición", skillCommunication: "Comunicación", skillSmallSided: "Juego reducido", skillConditioning: "Acondicionamiento", skillPressure: "Presión", filterMore: "Más" },
    favorites: { title: "Favoritos", subtitle: "Tus entrenamientos marcados como favoritos.", empty: "Aún no has marcado ningún entrenamiento como favorito." },
    calendar: { title: "Calendario", subtitle: "Programa tus entrenamientos por fecha.", schedule: "Programar", scheduleTitle: "Programar entrenamiento", date: "Fecha", empty: "No hay entrenamientos programados para este día.", scheduled: "Entrenamientos programados", remove: "Quitar" },
    season: { title: "Temporada", subtitle: "Define las fases de la temporada de cada equipo.", newPhase: "Nueva fase", phaseName: "Nombre de la fase", phaseColor: "Color", startDate: "Inicio", endDate: "Fin", currentPhase: "Fase actual", empty: "Aún no hay fases.", deleteConfirm: "¿Quitar esta fase?" },
    profile: { title: "Perfil", subtitle: "Edita los datos de tu cuenta.", fullName: "Nombre completo", email: "Correo electrónico", currentPassword: "Contraseña actual", newPassword: "Nueva contraseña", save: "Guardar cambios", saved: "Perfil actualizado.", changePassword: "Cambiar contraseña", wrongPassword: "La contraseña actual es incorrecta.", emailTaken: "Ese correo ya está en uso.", passwordSaved: "Contraseña cambiada." },
    settings: { title: "Configuración", subtitle: "Preferencias de tu cuenta.", account: "Cuenta", name: "Nombre", email: "Correo electrónico", appearance: "Apariencia", appearanceDesc: "Cambia entre tema claro y oscuro.", language: "Idioma" },
    errors: { rateLimited: "Demasiadas solicitudes ahora. Intenta de nuevo en unos instantes.", noCredits: "La clave de OpenAI no está configurada o no tiene créditos. Verifica la variable OPENAI_KEY.", aiError: "No se pudo procesar en este momento. Intenta de nuevo." },
    purchase: { title: "Confirma tu compra", subtitle: "Escribe el correo que usaste para comprar CoachAI Vôlei en Hotmart para continuar.", emailLabel: "Correo de la compra", emailPlaceholder: "tucorreo@ejemplo.com", verifyButton: "Verificar y continuar", verifying: "Verificando...", notFound: "No encontramos una compra aprobada con ese correo.", error: "No se pudo verificar en este momento. Intenta de nuevo en unos instantes.", supportHint: "¿Compraste y el correo no coincide? Contacta al soporte." },
    tour: { bannerTitle: "Descubre CoachAI en 2 minutos", bannerDesc: "Un recorrido rápido por lo esencial.", start: "Comenzar", stepOf: "Paso {n} de {total}", skip: "Saltar tutorial", back: "Atrás", next: "Siguiente", finish: "Finalizar", stepDashboardTitle: "Panel", stepDashboardDesc: "Aquí ves un resumen de tu trabajo: entrenamientos creados, jugadores seguidos y tus entrenamientos más recientes.", stepAiCoachTitle: "Asistente IA", stepAiCoachDesc: "Tu entrenador asistente. Describe el grupo, el tiempo y el objetivo — recibe una sesión completa con bloques, tiempos y puntos de coaching.", stepTrainingBuilderTitle: "Crear entrenamiento", stepTrainingBuilderDesc: "Arma un entrenamiento paso a paso respondiendo preguntas simples, y deja que la IA genere el plan completo con diagramas.", stepLibraryTitle: "Biblioteca", stepLibraryDesc: "Sesiones listas organizadas por tipo de habilidad — saque, ataque, bloqueo y más — listas para usar o adaptar.", stepTeamsTitle: "Equipos", stepTeamsDesc: "Registra tus equipos, define el sistema de juego y las prioridades de la temporada.", stepPlayersTitle: "Jugadores", stepPlayersDesc: "Sigue la plantilla de cada equipo y el desarrollo individual de los atletas.", stepCalendarTitle: "Calendario", stepCalendarDesc: "Programa tus entrenamientos por fecha y ten una vista semanal de tu planificación.", stepSeasonTitle: "Temporada", stepSeasonDesc: "Divide la temporada en fases y sigue en qué momento del ciclo está tu equipo." },
  },
  fr: {
    common: { save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", edit: "Modifier", create: "Créer", loading: "Chargement...", back: "Retour", next: "Suivant", search: "Rechercher", remove: "Retirer", none: "Aucun", optional: "facultatif" },
    nav: { work: "Travail", planning: "Planification", account: "Compte", dashboard: "Tableau de bord", aiCoach: "Assistant IA", trainingBuilder: "Créer un entraînement", library: "Bibliothèque", teams: "Équipes", players: "Joueurs", calendar: "Calendrier", season: "Saison", favorites: "Favoris", history: "Historique", profile: "Profil", settings: "Paramètres", signOut: "Déconnexion", role: "Entraîneur/euse", support: "Assistance" },
    auth: { loginTitle: "Connexion", loginSubtitle: "Accédez à votre tableau de bord d'entraîneur.", signupTitle: "Créer un compte", signupSubtitle: "Commencez à planifier des entraînements avec l'IA.", email: "E-mail", password: "Mot de passe", fullName: "Nom complet", loginButton: "Connexion", signupButton: "Créer un compte", noAccount: "Vous n'avez pas de compte ?", haveAccount: "Vous avez déjà un compte ?", loginLink: "Connexion", signupLink: "Créer un compte", loginError: "Impossible de se connecter.", signupError: "Impossible de créer votre compte." },
    dashboard: { greeting: "Bonjour", tagline: "Planifions le prochain entraînement de votre équipe.", notifications: "Notifications", newTraining: "Nouvel entraînement", metricTrainings: "Entraînements créés", metricObjectives: "Objectifs", metricPlayers: "Joueurs suivis", metricHours: "Heures économisées", thisMonth: "ce mois-ci", quickCreateTitle: "Création rapide", quickCreateSubtitle: "Créez un entraînement en quelques secondes", category: "Catégorie", objective: "Objectif", duration: "Durée", players: "Joueurs", quickCreateCta: "Créer l'entraînement", aiTitle: "Assistant IA", aiDescription: "Discutez avec CoachAI pour clarifier des doutes tactiques, ajuster un entraînement existant ou générer un plan complet, avec des diagrammes de terrain prêts à l'emploi.", aiCta: "Ouvrir l'assistant", popularTitle: "Populaires", popularServe: "Service", popularAttack: "Attaque", popularBlock: "Contre", popularSet: "Passe", popularDig: "Défense", popularReception: "Réception", popularRotation: "Rotation tactique", popularSmallSided: "Jeux réduits", recentTitle: "Entraînements récents", recentEmpty: "Vous n'avez encore créé aucun entraînement.", recentEmptyCta: "Créer mon premier entraînement", supportTitle: "Besoin d'aide ?", supportDesc: "Écrivez-nous par e-mail, nous répondrons à vos questions au plus vite.", supportCta: "Envoyer un e-mail" },
    teams: { title: "Équipes", subtitle: "Organisez vos équipes, systèmes de jeu et priorités de la saison.", newTeam: "Nouvelle équipe", emptyTitle: "Aucune équipe pour l'instant", emptyDesc: "Créez votre première équipe pour commencer à planifier des entraînements personnalisés.", dialogCreateTitle: "Nouvelle équipe", dialogEditTitle: "Modifier l'équipe", dialogSubtitle: "Définissez l'identité et le système de jeu de l'équipe.", name: "Nom de l'équipe", category: "Catégorie", season: "Saison", playSystem: "Système de jeu", priorities: "Priorités de la saison", playersCount: "joueurs", ready: "prêt", deleteTitle: "Supprimer l'équipe", deleteConfirm: "Voulez-vous vraiment supprimer cette équipe ? Les joueurs associés seront également supprimés. Cette action est irréversible.", createButton: "Créer l'équipe", saveButton: "Enregistrer les modifications" },
    players: { title: "Joueurs", subtitle: "Suivez l'effectif de chaque équipe.", newPlayer: "Nouveau joueur", emptyTitleNoTeam: "Créez d'abord une équipe", emptyDescNoTeam: "Vous avez besoin d'au moins une équipe avant d'ajouter des joueurs.", emptyTitle: "Aucun joueur pour l'instant", emptyDesc: "Ajoutez des joueurs pour suivre le développement de chacun.", addPlayer: "Ajouter un joueur", name: "Nom", team: "Équipe", position: "Poste", birthDate: "Date de naissance", dialogCreateTitle: "Nouveau joueur", dialogEditTitle: "Modifier le joueur", dialogSubtitle: "Informations de base sur l'athlète.", removeTitle: "Retirer le joueur", removeConfirm: "Voulez-vous vraiment retirer ce joueur ?", saveButton: "Enregistrer les modifications", createButton: "Ajouter" },
    trainingBuilder: { title: "Créer un entraînement", subtitle: "Répondez à quelques questions et CoachAI génère le plan complet avec des diagrammes.", stepCategory: "Catégorie", stepObjective: "Objectif", stepContext: "Contexte", stepMaterials: "Matériel", stepReview: "Révision", stepOf: "Étape {n} sur {total}", categoryLabel: "Catégorie", team: "Équipe", noTeam: "Aucune équipe spécifique", objectiveLabel: "Objectif de l'entraînement", objectivePlaceholder: "Décrivez l'objectif principal de l'entraînement...", playersLabel: "Nombre de joueurs", durationLabel: "Durée (min)", courtLabel: "Terrain", weekMomentLabel: "Moment de la semaine", materialsLabel: "Matériel disponible", materialsPlaceholder: "Ex : 12 chasubles, 20 plots, 6 ballons...", notesLabel: "Remarques", notesPlaceholder: "Restriction, blessure, focus particulier...", reviewTitle: "Révision", reviewDesc: "Vérifiez les informations avant de générer l'entraînement avec l'IA.", back: "Retour", next: "Suivant", generate: "Générer l'entraînement", generating: "Génération en cours...", categoryU6: "M6 (initiation)", categoryU11: "M11", categoryU14: "M14", categoryU16: "M16", categoryPro: "Professionnel", objectiveSuggestions: ["Réception de service", "Attaque en position 4", "Double bloc", "Passe et distribution", "Défense au sol", "Service flottant"], courtReduced: "Terrain réduit", courtAttack: "Zone d'attaque", courtHalf: "Demi-terrain", courtFull: "Terrain complet", momentPreSeason: "Pré-saison", momentMidWeek: "Milieu de semaine", momentMatchWeek: "Semaine de match", momentPost: "Après-match", },
    aiCoach: { title: "CoachAI", subtitle: "Votre assistant tactique", conversations: "Conversations", newConversation: "Nouvelle conversation", empty: "Aucune conversation pour l'instant.", placeholder: "Écrivez votre message...", suggestionsLabel: "Suggestions", deleteConfirm: "Supprimer cette conversation ?", noTeam: "Aucune équipe", suggestion1: "Créez un entraînement d'attaque en position 4 pour M14, 60 minutes", suggestion2: "Comment améliorer le double bloc de mon équipe ?", suggestion3: "J'ai besoin d'un échauffement de 15 minutes pour la pré-saison", trainingReady: 'C\'est prêt ! J\'ai préparé "{title}" avec {blocks} blocs et {duration} minutes. Jetez un œil au plan complet ci-dessous.' },
    trainingDoc: { category: "Catégorie", duration: "Durée", players: "Joueurs", court: "Terrain", intensity: "Intensité", materials: "Matériel", blocks: "Blocs de l'entraînement", coachingPoints: "Points clés", offensive: "Offensif", defensive: "Défensif", tacticalPrinciple: "Principe tactique", progressions: "Progressions", regressions: "Régressions", socioAffective: "Socio-affectif", notes: "Notes", print: "Imprimer", favorite: "Favori", favorited: "Favori", howTo: "Comment l'exécuter", step: "Étape", setup: "Contexte de l'exercice", noDiagram: "Diagramme détaillé bientôt disponible pour ce bloc." },
    history: { title: "Historique", subtitle: "Tous les entraînements que vous avez générés.", empty: "Aucun entraînement dans l'historique pour l'instant." },
    library: { title: "Bibliothèque", subtitle: "Séances prêtes à l'emploi et vos entraînements générés.", empty: "Aucun entraînement dans la bibliothèque pour l'instant.", useAsBase: "Utiliser comme base", searchPlaceholder: "Rechercher par titre ou objectif...", allCategories: "Toutes les catégories", readyMade: "Séances prêtes à l'emploi", myTrainings: "Mes entraînements", readyMadeBadge: "Séance prête à l'emploi", useTraining: "Utiliser cet entraînement", variants: "Variantes", harder: "Plus difficile", easier: "Plus facile", usingTemplate: "Préparation de votre entraînement...", notFound: "Entraînement introuvable.", backToLibrary: "Retour à la bibliothèque", useMessageUser: 'Je veux utiliser la séance prête à l\'emploi "{title}" ({category}).', useMessageAssistant: 'C\'est prêt ! J\'ai chargé "{title}" avec {blocks} blocs et {duration} minutes. Jetez un œil au plan complet ci-dessous.' , filterAll: "Tous", skillServe: "Service", skillPass: "Réception", skillSet: "Passe", skillAttack: "Attaque", skillBlock: "Bloc", skillDefense: "Défense", skillLibero: "Libéro", skillRotation: "Rotation", skillCoverage: "Couverture", skillTransition: "Transition", skillCommunication: "Communication", skillSmallSided: "Jeu réduit", skillConditioning: "Préparation physique", skillPressure: "Pression", filterMore: "Plus" },
    favorites: { title: "Favoris", subtitle: "Vos entraînements marqués comme favoris.", empty: "Vous n'avez encore mis aucun entraînement en favori." },
    calendar: { title: "Calendrier", subtitle: "Planifiez vos entraînements par date.", schedule: "Planifier", scheduleTitle: "Planifier l'entraînement", date: "Date", empty: "Aucun entraînement prévu pour ce jour.", scheduled: "Entraînements planifiés", remove: "Retirer" },
    season: { title: "Saison", subtitle: "Définissez les phases de saison de chaque équipe.", newPhase: "Nouvelle phase", phaseName: "Nom de la phase", phaseColor: "Couleur", startDate: "Début", endDate: "Fin", currentPhase: "Phase actuelle", empty: "Aucune phase pour l'instant.", deleteConfirm: "Retirer cette phase ?" },
    profile: { title: "Profil", subtitle: "Modifiez les informations de votre compte.", fullName: "Nom complet", email: "E-mail", currentPassword: "Mot de passe actuel", newPassword: "Nouveau mot de passe", save: "Enregistrer les modifications", saved: "Profil mis à jour.", changePassword: "Changer le mot de passe", wrongPassword: "Le mot de passe actuel est incorrect.", emailTaken: "Cet e-mail est déjà utilisé.", passwordSaved: "Mot de passe modifié." },
    settings: { title: "Paramètres", subtitle: "Préférences de votre compte.", account: "Compte", name: "Nom", email: "E-mail", appearance: "Apparence", appearanceDesc: "Basculez entre le thème clair et sombre.", language: "Langue" },
    errors: { rateLimited: "Trop de requêtes pour le moment. Réessayez dans un instant.", noCredits: "La clé OpenAI n'est pas configurée ou n'a plus de crédits. Vérifiez la variable OPENAI_KEY.", aiError: "Impossible de traiter la demande pour le moment. Réessayez." },
    purchase: { title: "Confirmez votre achat", subtitle: "Saisissez l'e-mail utilisé pour acheter CoachAI Vôlei sur Hotmart pour continuer.", emailLabel: "E-mail d'achat", emailPlaceholder: "votremail@exemple.com", verifyButton: "Vérifier et continuer", verifying: "Vérification...", notFound: "Nous n'avons trouvé aucun achat approuvé avec cet e-mail.", error: "Impossible de vérifier pour le moment. Réessayez dans un instant.", supportHint: "Vous avez acheté mais l'e-mail ne correspond pas ? Contactez le support." },
    tour: { bannerTitle: "Découvrez CoachAI en 2 minutes", bannerDesc: "Un tour rapide de l'essentiel.", start: "Commencer", stepOf: "Étape {n} sur {total}", skip: "Passer le tutoriel", back: "Retour", next: "Suivant", finish: "Terminer", stepDashboardTitle: "Tableau de bord", stepDashboardDesc: "Retrouvez ici un résumé de votre travail : entraînements créés, joueurs suivis et vos entraînements les plus récents.", stepAiCoachTitle: "Assistant IA", stepAiCoachDesc: "Votre coach assistant. Décrivez le groupe, le temps et l'objectif — obtenez une séance complète avec des blocs, des durées et des points de coaching.", stepTrainingBuilderTitle: "Créer un entraînement", stepTrainingBuilderDesc: "Construisez un entraînement étape par étape en répondant à des questions simples, et laissez l'IA générer le plan complet avec des diagrammes.", stepLibraryTitle: "Bibliothèque", stepLibraryDesc: "Séances prêtes à l'emploi organisées par type de compétence — service, attaque, contre et plus — prêtes à utiliser ou à adapter.", stepTeamsTitle: "Équipes", stepTeamsDesc: "Enregistrez vos équipes, définissez le système de jeu et les priorités de la saison.", stepPlayersTitle: "Joueurs", stepPlayersDesc: "Suivez l'effectif de chaque équipe et le développement individuel des athlètes.", stepCalendarTitle: "Calendrier", stepCalendarDesc: "Planifiez vos entraînements par date et ayez une vue hebdomadaire de votre planification.", stepSeasonTitle: "Saison", stepSeasonDesc: "Divisez la saison en phases et suivez à quel moment du cycle se trouve votre équipe." },
  },
  it: {
    common: { save: "Salva", cancel: "Annulla", delete: "Elimina", edit: "Modifica", create: "Crea", loading: "Caricamento...", back: "Indietro", next: "Avanti", search: "Cerca", remove: "Rimuovi", none: "Nessuno", optional: "facoltativo" },
    nav: { work: "Lavoro", planning: "Pianificazione", account: "Account", dashboard: "Pannello", aiCoach: "Assistente IA", trainingBuilder: "Crea allenamento", library: "Libreria", teams: "Squadre", players: "Giocatori", calendar: "Calendario", season: "Stagione", favorites: "Preferiti", history: "Cronologia", profile: "Profilo", settings: "Impostazioni", signOut: "Esci", role: "Allenatore/trice", support: "Assistenza" },
    auth: { loginTitle: "Accedi", loginSubtitle: "Accedi al tuo pannello da allenatore.", signupTitle: "Crea account", signupSubtitle: "Inizia a pianificare allenamenti con l'IA.", email: "E-mail", password: "Password", fullName: "Nome completo", loginButton: "Accedi", signupButton: "Crea account", noAccount: "Non hai un account?", haveAccount: "Hai già un account?", loginLink: "Accedi", signupLink: "Crea account", loginError: "Non è stato possibile accedere.", signupError: "Non è stato possibile creare il tuo account." },
    dashboard: { greeting: "Ciao", tagline: "Pianifichiamo il prossimo allenamento della tua squadra.", notifications: "Notifiche", newTraining: "Nuovo allenamento", metricTrainings: "Allenamenti creati", metricObjectives: "Obiettivi", metricPlayers: "Giocatori seguiti", metricHours: "Ore risparmiate", thisMonth: "questo mese", quickCreateTitle: "Creazione rapida", quickCreateSubtitle: "Crea un allenamento in pochi secondi", category: "Categoria", objective: "Obiettivo", duration: "Durata", players: "Giocatori", quickCreateCta: "Crea allenamento", aiTitle: "Assistente IA", aiDescription: "Parla con CoachAI per chiarire dubbi tattici, modificare un allenamento esistente o generare un piano da zero, con diagrammi del campo pronti.", aiCta: "Apri assistente", popularTitle: "Popolari", popularServe: "Battuta", popularAttack: "Attacco", popularBlock: "Muro", popularSet: "Palleggio", popularDig: "Difesa", popularReception: "Ricezione", popularRotation: "Rotazione tattica", popularSmallSided: "Giochi ridotti", recentTitle: "Allenamenti recenti", recentEmpty: "Non hai ancora creato nessun allenamento.", recentEmptyCta: "Crea il mio primo allenamento", supportTitle: "Hai bisogno di aiuto?", supportDesc: "Scrivici via e-mail e risponderemo alle tue domande il prima possibile.", supportCta: "Invia e-mail" },
    teams: { title: "Squadre", subtitle: "Organizza le tue squadre, i sistemi di gioco e le priorità della stagione.", newTeam: "Nuova squadra", emptyTitle: "Nessuna squadra ancora", emptyDesc: "Crea la tua prima squadra per iniziare a pianificare allenamenti personalizzati.", dialogCreateTitle: "Nuova squadra", dialogEditTitle: "Modifica squadra", dialogSubtitle: "Definisci l'identità e il sistema di gioco della squadra.", name: "Nome della squadra", category: "Categoria", season: "Stagione", playSystem: "Sistema di gioco", priorities: "Priorità della stagione", playersCount: "giocatori", ready: "pronto", deleteTitle: "Elimina squadra", deleteConfirm: "Sei sicuro di voler eliminare questa squadra? Anche i giocatori collegati verranno rimossi. Questa azione non può essere annullata.", createButton: "Crea squadra", saveButton: "Salva modifiche" },
    players: { title: "Giocatori", subtitle: "Tieni traccia della rosa di ogni squadra.", newPlayer: "Nuovo giocatore", emptyTitleNoTeam: "Crea prima una squadra", emptyDescNoTeam: "Hai bisogno di almeno una squadra prima di aggiungere giocatori.", emptyTitle: "Nessun giocatore ancora", emptyDesc: "Aggiungi giocatori per seguire lo sviluppo di ciascuno.", addPlayer: "Aggiungi giocatore", name: "Nome", team: "Squadra", position: "Ruolo", birthDate: "Data di nascita", dialogCreateTitle: "Nuovo giocatore", dialogEditTitle: "Modifica giocatore", dialogSubtitle: "Informazioni di base sull'atleta.", removeTitle: "Rimuovi giocatore", removeConfirm: "Sei sicuro di voler rimuovere questo giocatore?", saveButton: "Salva modifiche", createButton: "Aggiungi" },
    trainingBuilder: { title: "Crea allenamento", subtitle: "Rispondi ad alcune domande e CoachAI crea il piano completo con i diagrammi.", stepCategory: "Categoria", stepObjective: "Obiettivo", stepContext: "Contesto", stepMaterials: "Materiali", stepReview: "Revisione", stepOf: "Passo {n} di {total}", categoryLabel: "Categoria", team: "Squadra", noTeam: "Nessuna squadra specifica", objectiveLabel: "Obiettivo dell'allenamento", objectivePlaceholder: "Descrivi l'obiettivo principale dell'allenamento...", playersLabel: "Numero di giocatori", durationLabel: "Durata (min)", courtLabel: "Campo", weekMomentLabel: "Momento della settimana", materialsLabel: "Materiali disponibili", materialsPlaceholder: "Es: 12 pettorine, 20 coni, 6 palloni...", notesLabel: "Note", notesPlaceholder: "Eventuali restrizioni, infortuni, focus speciale...", reviewTitle: "Revisione", reviewDesc: "Controlla i dati prima di generare l'allenamento con l'IA.", back: "Indietro", next: "Avanti", generate: "Genera allenamento", generating: "Generazione in corso...", categoryU6: "Under 6 (avviamento)", categoryU11: "Under 11", categoryU14: "Under 14", categoryU16: "Under 16", categoryPro: "Professionisti", objectiveSuggestions: ["Ricezione del servizio", "Attacco in posizione 4", "Muro doppio", "Alzata e distribuzione", "Difesa a terra", "Servizio float"], courtReduced: "Campo ridotto", courtAttack: "Zona d'attacco", courtHalf: "Mezzo campo", courtFull: "Campo intero", momentPreSeason: "Pre-stagione", momentMidWeek: "Metà settimana", momentMatchWeek: "Settimana di partita", momentPost: "Post-partita", },
    aiCoach: { title: "CoachAI", subtitle: "Il tuo assistente tattico", conversations: "Conversazioni", newConversation: "Nuova conversazione", empty: "Nessuna conversazione ancora.", placeholder: "Scrivi il tuo messaggio...", suggestionsLabel: "Suggerimenti", deleteConfirm: "Eliminare questa conversazione?", noTeam: "Nessuna squadra", suggestion1: "Crea un allenamento di attacco in posizione 4 per Under 14, 60 minuti", suggestion2: "Come posso migliorare il muro doppio della mia squadra?", suggestion3: "Mi serve un riscaldamento di 15 minuti per la pre-stagione", trainingReady: 'Fatto! Ho preparato "{title}" con {blocks} blocchi e {duration} minuti. Dai un\'occhiata al piano completo qui sotto.' },
    trainingDoc: { category: "Categoria", duration: "Durata", players: "Giocatori", court: "Campo", intensity: "Intensità", materials: "Materiali", blocks: "Blocchi dell'allenamento", coachingPoints: "Punti chiave", offensive: "Offensivo", defensive: "Difensivo", tacticalPrinciple: "Principio tattico", progressions: "Progressioni", regressions: "Regressioni", socioAffective: "Socio-affettivo", notes: "Note", print: "Stampa", favorite: "Preferito", favorited: "Preferito", howTo: "Come eseguirlo", step: "Passo", setup: "Contesto dell'esercizio", noDiagram: "Diagramma dettagliato in arrivo per questo blocco." },
    history: { title: "Cronologia", subtitle: "Tutti gli allenamenti che hai generato.", empty: "Nessun allenamento ancora nella cronologia." },
    library: { title: "Libreria", subtitle: "Sessioni pronte e gli allenamenti che hai generato.", empty: "Nessun allenamento ancora nella libreria.", useAsBase: "Usa come base", searchPlaceholder: "Cerca per titolo o obiettivo...", allCategories: "Tutte le categorie", readyMade: "Sessioni pronte", myTrainings: "I miei allenamenti", readyMadeBadge: "Sessione pronta", useTraining: "Usa questo allenamento", variants: "Varianti", harder: "Più difficile", easier: "Più facile", usingTemplate: "Preparazione del tuo allenamento...", notFound: "Allenamento non trovato.", backToLibrary: "Torna alla libreria", useMessageUser: 'Voglio usare la sessione pronta "{title}" ({category}).', useMessageAssistant: 'Fatto! Ho caricato "{title}" con {blocks} blocchi e {duration} minuti. Dai un\'occhiata al piano completo qui sotto.' , filterAll: "Tutti", skillServe: "Servizio", skillPass: "Ricezione", skillSet: "Alzata", skillAttack: "Attacco", skillBlock: "Muro", skillDefense: "Difesa", skillLibero: "Libero", skillRotation: "Rotazione", skillCoverage: "Copertura", skillTransition: "Transizione", skillCommunication: "Comunicazione", skillSmallSided: "Gioco ridotto", skillConditioning: "Condizionamento", skillPressure: "Pressione", filterMore: "Altro" },
    favorites: { title: "Preferiti", subtitle: "I tuoi allenamenti contrassegnati come preferiti.", empty: "Non hai ancora aggiunto allenamenti ai preferiti." },
    calendar: { title: "Calendario", subtitle: "Programma i tuoi allenamenti per data.", schedule: "Programma", scheduleTitle: "Programma allenamento", date: "Data", empty: "Nessun allenamento programmato per questo giorno.", scheduled: "Allenamenti programmati", remove: "Rimuovi" },
    season: { title: "Stagione", subtitle: "Definisci le fasi della stagione di ogni squadra.", newPhase: "Nuova fase", phaseName: "Nome della fase", phaseColor: "Colore", startDate: "Inizio", endDate: "Fine", currentPhase: "Fase attuale", empty: "Nessuna fase ancora.", deleteConfirm: "Rimuovere questa fase?" },
    profile: { title: "Profilo", subtitle: "Modifica i dati del tuo account.", fullName: "Nome completo", email: "E-mail", currentPassword: "Password attuale", newPassword: "Nuova password", save: "Salva modifiche", saved: "Profilo aggiornato.", changePassword: "Cambia password", wrongPassword: "La password attuale non è corretta.", emailTaken: "Questa email è già in uso.", passwordSaved: "Password modificata." },
    settings: { title: "Impostazioni", subtitle: "Preferenze del tuo account.", account: "Account", name: "Nome", email: "E-mail", appearance: "Aspetto", appearanceDesc: "Passa dal tema chiaro a quello scuro.", language: "Lingua" },
    errors: { rateLimited: "Troppe richieste al momento. Riprova tra poco.", noCredits: "La chiave OpenAI non è configurata o non ha crediti. Controlla la variabile OPENAI_KEY.", aiError: "Impossibile elaborare la richiesta ora. Riprova." },
    purchase: { title: "Conferma il tuo acquisto", subtitle: "Inserisci l'e-mail usata per acquistare CoachAI Vôlei su Hotmart per continuare.", emailLabel: "E-mail dell'acquisto", emailPlaceholder: "tuaemail@esempio.com", verifyButton: "Verifica e continua", verifying: "Verifica in corso...", notFound: "Non abbiamo trovato un acquisto approvato con questa e-mail.", error: "Impossibile verificare ora. Riprova tra poco.", supportHint: "Hai acquistato ma l'e-mail non corrisponde? Contatta il supporto." },
    tour: { bannerTitle: "Scopri CoachAI in 2 minuti", bannerDesc: "Un tour rapido tra le funzioni essenziali.", start: "Inizia", stepOf: "Passo {n} di {total}", skip: "Salta il tutorial", back: "Indietro", next: "Avanti", finish: "Fine", stepDashboardTitle: "Pannello", stepDashboardDesc: "Qui trovi un riepilogo del tuo lavoro: allenamenti creati, giocatori seguiti e i tuoi allenamenti più recenti.", stepAiCoachTitle: "Assistente IA", stepAiCoachDesc: "Il tuo allenatore assistente. Descrivi il gruppo, il tempo e l'obiettivo — ricevi una sessione completa con blocchi, tempi e punti di coaching.", stepTrainingBuilderTitle: "Crea allenamento", stepTrainingBuilderDesc: "Crea un allenamento passo dopo passo rispondendo a domande semplici, e lascia che l'IA generi il piano completo con diagrammi.", stepLibraryTitle: "Libreria", stepLibraryDesc: "Sessioni pronte organizzate per tipo di abilità — battuta, attacco, muro e altro — pronte da usare o adattare.", stepTeamsTitle: "Squadre", stepTeamsDesc: "Registra le tue squadre, definisci il sistema di gioco e le priorità della stagione.", stepPlayersTitle: "Giocatori", stepPlayersDesc: "Segui la rosa di ogni squadra e lo sviluppo individuale degli atleti.", stepCalendarTitle: "Calendario", stepCalendarDesc: "Pianifica i tuoi allenamenti per data e ottieni una vista settimanale della pianificazione.", stepSeasonTitle: "Stagione", stepSeasonDesc: "Dividi la stagione in fasi e segui in quale momento del ciclo si trova la tua squadra." },
  },
  de: {
    common: { save: "Speichern", cancel: "Abbrechen", delete: "Löschen", edit: "Bearbeiten", create: "Erstellen", loading: "Lädt...", back: "Zurück", next: "Weiter", search: "Suchen", remove: "Entfernen", none: "Keine", optional: "optional" },
    nav: { work: "Arbeit", planning: "Planung", account: "Konto", dashboard: "Übersicht", aiCoach: "KI-Assistent", trainingBuilder: "Training erstellen", library: "Bibliothek", teams: "Teams", players: "Spieler", calendar: "Kalender", season: "Saison", favorites: "Favoriten", history: "Verlauf", profile: "Profil", settings: "Einstellungen", signOut: "Abmelden", role: "Trainer/in", support: "Support" },
    auth: { loginTitle: "Anmelden", loginSubtitle: "Greife auf dein Trainer-Dashboard zu.", signupTitle: "Konto erstellen", signupSubtitle: "Beginne, Trainings mit KI zu planen.", email: "E-Mail", password: "Passwort", fullName: "Vollständiger Name", loginButton: "Anmelden", signupButton: "Konto erstellen", noAccount: "Noch kein Konto?", haveAccount: "Bereits ein Konto?", loginLink: "Anmelden", signupLink: "Konto erstellen", loginError: "Anmeldung nicht möglich.", signupError: "Konto konnte nicht erstellt werden." },
    dashboard: { greeting: "Hallo", tagline: "Lass uns das nächste Training deines Teams planen.", notifications: "Benachrichtigungen", newTraining: "Neues Training", metricTrainings: "Erstellte Trainings", metricObjectives: "Ziele", metricPlayers: "Betreute Spieler", metricHours: "Gesparte Stunden", thisMonth: "diesen Monat", quickCreateTitle: "Schnellerstellung", quickCreateSubtitle: "Erstelle ein Training in Sekunden", category: "Kategorie", objective: "Ziel", duration: "Dauer", players: "Spieler", quickCreateCta: "Training erstellen", aiTitle: "KI-Assistent", aiDescription: "Chatte mit CoachAI, um taktische Fragen zu klären, ein bestehendes Training anzupassen oder einen Plan von Grund auf zu erstellen — mit fertigen Feld-Diagrammen.", aiCta: "Assistent öffnen", popularTitle: "Beliebt", popularServe: "Aufschlag", popularAttack: "Angriff", popularBlock: "Block", popularSet: "Zuspiel", popularDig: "Abwehr", popularReception: "Annahme", popularRotation: "Taktische Rotation", popularSmallSided: "Kleine Spielformen", recentTitle: "Letzte Trainings", recentEmpty: "Du hast noch kein Training erstellt.", recentEmptyCta: "Mein erstes Training erstellen", supportTitle: "Brauchst du Hilfe?", supportDesc: "Schreib uns eine E-Mail und wir beantworten deine Fragen so schnell wie möglich.", supportCta: "E-Mail senden" },
    teams: { title: "Teams", subtitle: "Organisiere deine Teams, Spielsysteme und Saisonprioritäten.", newTeam: "Neues Team", emptyTitle: "Noch keine Teams", emptyDesc: "Erstelle dein erstes Team, um mit der Planung personalisierter Trainings zu beginnen.", dialogCreateTitle: "Neues Team", dialogEditTitle: "Team bearbeiten", dialogSubtitle: "Lege die Identität und das Spielsystem des Teams fest.", name: "Teamname", category: "Kategorie", season: "Saison", playSystem: "Spielsystem", priorities: "Saisonprioritäten", playersCount: "Spieler", ready: "bereit", deleteTitle: "Team löschen", deleteConfirm: "Möchtest du dieses Team wirklich löschen? Verknüpfte Spieler werden ebenfalls entfernt. Dies kann nicht rückgängig gemacht werden.", createButton: "Team erstellen", saveButton: "Änderungen speichern" },
    players: { title: "Spieler", subtitle: "Verfolge den Kader jedes Teams.", newPlayer: "Neuer Spieler", emptyTitleNoTeam: "Erstelle zuerst ein Team", emptyDescNoTeam: "Du benötigst mindestens ein Team, bevor du Spieler hinzufügen kannst.", emptyTitle: "Noch keine Spieler", emptyDesc: "Füge Spieler hinzu, um die Entwicklung jedes Einzelnen zu verfolgen.", addPlayer: "Spieler hinzufügen", name: "Name", team: "Team", position: "Position", birthDate: "Geburtsdatum", dialogCreateTitle: "Neuer Spieler", dialogEditTitle: "Spieler bearbeiten", dialogSubtitle: "Grundlegende Informationen zum Athleten.", removeTitle: "Spieler entfernen", removeConfirm: "Möchtest du diesen Spieler wirklich entfernen?", saveButton: "Änderungen speichern", createButton: "Hinzufügen" },
    trainingBuilder: { title: "Training erstellen", subtitle: "Beantworte ein paar Fragen und CoachAI erstellt den vollständigen Plan mit Diagrammen.", stepCategory: "Kategorie", stepObjective: "Ziel", stepContext: "Kontext", stepMaterials: "Material", stepReview: "Überprüfung", stepOf: "Schritt {n} von {total}", categoryLabel: "Kategorie", team: "Team", noTeam: "Kein bestimmtes Team", objectiveLabel: "Trainingsziel", objectivePlaceholder: "Beschreibe das Hauptziel des Trainings...", playersLabel: "Anzahl der Spieler", durationLabel: "Dauer (Min.)", courtLabel: "Feld", weekMomentLabel: "Zeitpunkt der Woche", materialsLabel: "Verfügbares Material", materialsPlaceholder: "Z. B.: 12 Leibchen, 20 Hütchen, 6 Bälle...", notesLabel: "Anmerkungen", notesPlaceholder: "Einschränkungen, Verletzungen, besonderer Fokus...", reviewTitle: "Überprüfung", reviewDesc: "Überprüfe die Angaben, bevor das Training mit KI generiert wird.", back: "Zurück", next: "Weiter", generate: "Training generieren", generating: "Training wird generiert...", categoryU6: "U6 (Einstieg)", categoryU11: "U11", categoryU14: "U14", categoryU16: "U16", categoryPro: "Profis", objectiveSuggestions: ["Aufschlagannahme", "Angriff Position 4", "Doppelblock", "Zuspiel und Verteilung", "Feldabwehr", "Flatteraufschlag"], courtReduced: "Verkleinertes Feld", courtAttack: "Angriffszone", courtHalf: "Halbfeld", courtFull: "Ganzes Feld", momentPreSeason: "Vorsaison", momentMidWeek: "Wochenmitte", momentMatchWeek: "Spielwoche", momentPost: "Nach dem Spiel", },
    aiCoach: { title: "CoachAI", subtitle: "Dein taktischer Assistent", conversations: "Unterhaltungen", newConversation: "Neue Unterhaltung", empty: "Noch keine Unterhaltungen.", placeholder: "Schreibe deine Nachricht...", suggestionsLabel: "Vorschläge", deleteConfirm: "Diese Unterhaltung löschen?", noTeam: "Kein Team", suggestion1: "Erstelle ein Angriffstraining Position 4 für U14, 60 Minuten", suggestion2: "Wie verbessere ich den Doppelblock meines Teams?", suggestion3: "Ich brauche ein 15-minütiges Aufwärmen für die Vorsaison", trainingReady: 'Fertig! Ich habe "{title}" mit {blocks} Blöcken und {duration} Minuten vorbereitet. Schau dir unten den vollständigen Plan an.' },
    trainingDoc: { category: "Kategorie", duration: "Dauer", players: "Spieler", court: "Feld", intensity: "Intensität", materials: "Material", blocks: "Trainingsblöcke", coachingPoints: "Coaching-Punkte", offensive: "Offensiv", defensive: "Defensiv", tacticalPrinciple: "Taktisches Prinzip", progressions: "Steigerungen", regressions: "Vereinfachungen", socioAffective: "Sozial-affektiv", notes: "Notizen", print: "Drucken", favorite: "Favorisieren", favorited: "Favorisiert", howTo: "So führst du es aus", step: "Schritt", setup: "Ausgangssituation", noDiagram: "Detailliertes Diagramm für diesen Block folgt in Kürze." },
    history: { title: "Verlauf", subtitle: "Alle Trainings, die du generiert hast.", empty: "Noch keine Trainings im Verlauf." },
    library: { title: "Bibliothek", subtitle: "Fertige Einheiten und deine bereits erstellten Trainings.", empty: "Noch keine Trainings in der Bibliothek.", useAsBase: "Als Basis verwenden", searchPlaceholder: "Nach Titel oder Ziel suchen...", allCategories: "Alle Kategorien", readyMade: "Fertige Einheiten", myTrainings: "Meine Trainings", readyMadeBadge: "Fertige Einheit", useTraining: "Dieses Training verwenden", variants: "Varianten", harder: "Schwerer", easier: "Leichter", usingTemplate: "Dein Training wird vorbereitet...", notFound: "Training nicht gefunden.", backToLibrary: "Zurück zur Bibliothek", useMessageUser: 'Ich möchte die fertige Einheit "{title}" ({category}) verwenden.', useMessageAssistant: 'Fertig! Ich habe "{title}" mit {blocks} Blöcken und {duration} Minuten geladen. Schau dir unten den vollständigen Plan an.' , filterAll: "Alle", skillServe: "Aufschlag", skillPass: "Annahme", skillSet: "Zuspiel", skillAttack: "Angriff", skillBlock: "Block", skillDefense: "Abwehr", skillLibero: "Libero", skillRotation: "Rotation", skillCoverage: "Absicherung", skillTransition: "Übergang", skillCommunication: "Kommunikation", skillSmallSided: "Kleines Spiel", skillConditioning: "Konditionstraining", skillPressure: "Drucksituation", filterMore: "Mehr" },
    favorites: { title: "Favoriten", subtitle: "Deine als Favorit markierten Trainings.", empty: "Du hast noch keine Trainings favorisiert." },
    calendar: { title: "Kalender", subtitle: "Plane deine Trainings nach Datum.", schedule: "Einplanen", scheduleTitle: "Training einplanen", date: "Datum", empty: "Keine Trainings für diesen Tag geplant.", scheduled: "Geplante Trainings", remove: "Entfernen" },
    season: { title: "Saison", subtitle: "Lege die Saisonphasen jedes Teams fest.", newPhase: "Neue Phase", phaseName: "Phasenname", phaseColor: "Farbe", startDate: "Beginn", endDate: "Ende", currentPhase: "Aktuelle Phase", empty: "Noch keine Phasen.", deleteConfirm: "Diese Phase entfernen?" },
    profile: { title: "Profil", subtitle: "Bearbeite deine Kontodaten.", fullName: "Vollständiger Name", email: "E-Mail", currentPassword: "Aktuelles Passwort", newPassword: "Neues Passwort", save: "Änderungen speichern", saved: "Profil aktualisiert.", changePassword: "Passwort ändern", wrongPassword: "Das aktuelle Passwort ist falsch.", emailTaken: "Diese E-Mail wird bereits verwendet.", passwordSaved: "Passwort geändert." },
    settings: { title: "Einstellungen", subtitle: "Präferenzen deines Kontos.", account: "Konto", name: "Name", email: "E-Mail", appearance: "Erscheinungsbild", appearanceDesc: "Wechsle zwischen hellem und dunklem Design.", language: "Sprache" },
    errors: { rateLimited: "Gerade zu viele Anfragen. Versuche es in Kürze erneut.", noCredits: "Der OpenAI-Schlüssel ist nicht konfiguriert oder hat kein Guthaben mehr. Überprüfe die Variable OPENAI_KEY.", aiError: "Konnte gerade nicht verarbeitet werden. Versuche es erneut." },
    purchase: { title: "Bestätige deinen Kauf", subtitle: "Gib die E-Mail-Adresse ein, mit der du CoachAI Vôlei auf Hotmart gekauft hast, um fortzufahren.", emailLabel: "Kauf-E-Mail", emailPlaceholder: "deine@email.com", verifyButton: "Überprüfen und fortfahren", verifying: "Wird überprüft...", notFound: "Wir konnten keinen genehmigten Kauf mit dieser E-Mail finden.", error: "Konnte gerade nicht überprüft werden. Versuche es in Kürze erneut.", supportHint: "Gekauft, aber die E-Mail stimmt nicht überein? Kontaktiere den Support." },
    tour: { bannerTitle: "Entdecke CoachAI in 2 Minuten", bannerDesc: "Eine kurze Tour durch die wichtigsten Funktionen.", start: "Starten", stepOf: "Schritt {n} von {total}", skip: "Tutorial überspringen", back: "Zurück", next: "Weiter", finish: "Fertig", stepDashboardTitle: "Übersicht", stepDashboardDesc: "Hier siehst du eine Zusammenfassung deiner Arbeit: erstellte Trainings, verfolgte Spieler und deine neuesten Trainings.", stepAiCoachTitle: "KI-Assistent", stepAiCoachDesc: "Dein Trainerassistent. Beschreibe die Gruppe, die Zeit und das Ziel — erhalte eine vollständige Einheit mit Blöcken, Zeiten und Coaching-Punkten.", stepTrainingBuilderTitle: "Training erstellen", stepTrainingBuilderDesc: "Erstelle Schritt für Schritt ein Training, indem du einfache Fragen beantwortest, und lass die KI den vollständigen Plan mit Diagrammen erzeugen.", stepLibraryTitle: "Bibliothek", stepLibraryDesc: "Fertige Einheiten, organisiert nach Fertigkeit — Aufschlag, Angriff, Block und mehr — bereit zur Nutzung oder Anpassung.", stepTeamsTitle: "Teams", stepTeamsDesc: "Erfasse deine Teams, lege das Spielsystem und die Saisonprioritäten fest.", stepPlayersTitle: "Spieler", stepPlayersDesc: "Verfolge den Kader jedes Teams und die individuelle Entwicklung der Athleten.", stepCalendarTitle: "Kalender", stepCalendarDesc: "Plane deine Trainings nach Datum und erhalte eine Wochenübersicht deiner Planung.", stepSeasonTitle: "Saison", stepSeasonDesc: "Teile die Saison in Phasen ein und verfolge, in welcher Phase des Zyklus sich dein Team befindet." },
  },
};
